// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package uploadMocks

import (
	"context"
	"time"

	"github.com/mandacode-labs/mdrive/internal/core/node"
	"github.com/mandacode-labs/mdrive/internal/upload"
	mock "github.com/stretchr/testify/mock"
)

// NewClientMock creates a new instance of ClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientMock {
	mock := &ClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClientMock is an autogenerated mock type for the Client type
type ClientMock struct {
	mock.Mock
}

type ClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientMock) EXPECT() *ClientMock_Expecter {
	return &ClientMock_Expecter{mock: &_m.Mock}
}

// CompleteUpload provides a mock function for the type ClientMock
func (_mock *ClientMock) CompleteUpload(ctx context.Context, userID string, driveID string, uploadID string, contentLength int64, checksum *string) (*node.Node, error) {
	ret := _mock.Called(ctx, userID, driveID, uploadID, contentLength, checksum)

	if len(ret) == 0 {
		panic("no return value specified for CompleteUpload")
	}

	var r0 *node.Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64, *string) (*node.Node, error)); ok {
		return returnFunc(ctx, userID, driveID, uploadID, contentLength, checksum)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64, *string) *node.Node); ok {
		r0 = returnFunc(ctx, userID, driveID, uploadID, contentLength, checksum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*node.Node)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, int64, *string) error); ok {
		r1 = returnFunc(ctx, userID, driveID, uploadID, contentLength, checksum)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientMock_CompleteUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteUpload'
type ClientMock_CompleteUpload_Call struct {
	*mock.Call
}

// CompleteUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - driveID string
//   - uploadID string
//   - contentLength int64
//   - checksum *string
func (_e *ClientMock_Expecter) CompleteUpload(ctx interface{}, userID interface{}, driveID interface{}, uploadID interface{}, contentLength interface{}, checksum interface{}) *ClientMock_CompleteUpload_Call {
	return &ClientMock_CompleteUpload_Call{Call: _e.mock.On("CompleteUpload", ctx, userID, driveID, uploadID, contentLength, checksum)}
}

func (_c *ClientMock_CompleteUpload_Call) Run(run func(ctx context.Context, userID string, driveID string, uploadID string, contentLength int64, checksum *string)) *ClientMock_CompleteUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 *string
		if args[5] != nil {
			arg5 = args[5].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *ClientMock_CompleteUpload_Call) Return(node1 *node.Node, err error) *ClientMock_CompleteUpload_Call {
	_c.Call.Return(node1, err)
	return _c
}

func (_c *ClientMock_CompleteUpload_Call) RunAndReturn(run func(ctx context.Context, userID string, driveID string, uploadID string, contentLength int64, checksum *string) (*node.Node, error)) *ClientMock_CompleteUpload_Call {
	_c.Call.Return(run)
	return _c
}

// InitiateUpload provides a mock function for the type ClientMock
func (_mock *ClientMock) InitiateUpload(ctx context.Context, userID string, driveID string, destPath string, contentType *string, contentLength *int64, expiry time.Duration) (upload.PresignInfo, error) {
	ret := _mock.Called(ctx, userID, driveID, destPath, contentType, contentLength, expiry)

	if len(ret) == 0 {
		panic("no return value specified for InitiateUpload")
	}

	var r0 upload.PresignInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *string, *int64, time.Duration) (upload.PresignInfo, error)); ok {
		return returnFunc(ctx, userID, driveID, destPath, contentType, contentLength, expiry)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *string, *int64, time.Duration) upload.PresignInfo); ok {
		r0 = returnFunc(ctx, userID, driveID, destPath, contentType, contentLength, expiry)
	} else {
		r0 = ret.Get(0).(upload.PresignInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, *string, *int64, time.Duration) error); ok {
		r1 = returnFunc(ctx, userID, driveID, destPath, contentType, contentLength, expiry)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientMock_InitiateUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitiateUpload'
type ClientMock_InitiateUpload_Call struct {
	*mock.Call
}

// InitiateUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - driveID string
//   - destPath string
//   - contentType *string
//   - contentLength *int64
//   - expiry time.Duration
func (_e *ClientMock_Expecter) InitiateUpload(ctx interface{}, userID interface{}, driveID interface{}, destPath interface{}, contentType interface{}, contentLength interface{}, expiry interface{}) *ClientMock_InitiateUpload_Call {
	return &ClientMock_InitiateUpload_Call{Call: _e.mock.On("InitiateUpload", ctx, userID, driveID, destPath, contentType, contentLength, expiry)}
}

func (_c *ClientMock_InitiateUpload_Call) Run(run func(ctx context.Context, userID string, driveID string, destPath string, contentType *string, contentLength *int64, expiry time.Duration)) *ClientMock_InitiateUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		var arg5 *int64
		if args[5] != nil {
			arg5 = args[5].(*int64)
		}
		var arg6 time.Duration
		if args[6] != nil {
			arg6 = args[6].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *ClientMock_InitiateUpload_Call) Return(presignInfo upload.PresignInfo, err error) *ClientMock_InitiateUpload_Call {
	_c.Call.Return(presignInfo, err)
	return _c
}

func (_c *ClientMock_InitiateUpload_Call) RunAndReturn(run func(ctx context.Context, userID string, driveID string, destPath string, contentType *string, contentLength *int64, expiry time.Duration) (upload.PresignInfo, error)) *ClientMock_InitiateUpload_Call {
	_c.Call.Return(run)
	return _c
}

// PresignDownload provides a mock function for the type ClientMock
func (_mock *ClientMock) PresignDownload(ctx context.Context, userID string, driveID string, path string, expiry time.Duration) (upload.PresignInfo, error) {
	ret := _mock.Called(ctx, userID, driveID, path, expiry)

	if len(ret) == 0 {
		panic("no return value specified for PresignDownload")
	}

	var r0 upload.PresignInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, time.Duration) (upload.PresignInfo, error)); ok {
		return returnFunc(ctx, userID, driveID, path, expiry)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, time.Duration) upload.PresignInfo); ok {
		r0 = returnFunc(ctx, userID, driveID, path, expiry)
	} else {
		r0 = ret.Get(0).(upload.PresignInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, userID, driveID, path, expiry)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientMock_PresignDownload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignDownload'
type ClientMock_PresignDownload_Call struct {
	*mock.Call
}

// PresignDownload is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - driveID string
//   - path string
//   - expiry time.Duration
func (_e *ClientMock_Expecter) PresignDownload(ctx interface{}, userID interface{}, driveID interface{}, path interface{}, expiry interface{}) *ClientMock_PresignDownload_Call {
	return &ClientMock_PresignDownload_Call{Call: _e.mock.On("PresignDownload", ctx, userID, driveID, path, expiry)}
}

func (_c *ClientMock_PresignDownload_Call) Run(run func(ctx context.Context, userID string, driveID string, path string, expiry time.Duration)) *ClientMock_PresignDownload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Duration
		if args[4] != nil {
			arg4 = args[4].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ClientMock_PresignDownload_Call) Return(presignInfo upload.PresignInfo, err error) *ClientMock_PresignDownload_Call {
	_c.Call.Return(presignInfo, err)
	return _c
}

func (_c *ClientMock_PresignDownload_Call) RunAndReturn(run func(ctx context.Context, userID string, driveID string, path string, expiry time.Duration) (upload.PresignInfo, error)) *ClientMock_PresignDownload_Call {
	_c.Call.Return(run)
	return _c
}
