// Code generated by ogen, DO NOT EDIT.

package apiv1

import (
	"io"
	"net/url"
	"time"

	"github.com/go-faster/errors"
)

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

type CatOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s CatOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// DeleteDriveNoContent is response for DeleteDrive operation.
type DeleteDriveNoContent struct{}

// Ref: #/components/schemas/DirContent
type DirContent struct {
	Entries []DirEntry `json:"entries"`
}

// GetEntries returns the value of Entries.
func (s *DirContent) GetEntries() []DirEntry {
	return s.Entries
}

// SetEntries sets the value of Entries.
func (s *DirContent) SetEntries(val []DirEntry) {
	s.Entries = val
}

// Ref: #/components/schemas/DirEntry
type DirEntry struct {
	InodeID OptString `json:"inodeID"`
	Name    OptString `json:"name"`
	Type    OptString `json:"type"`
}

// GetInodeID returns the value of InodeID.
func (s *DirEntry) GetInodeID() OptString {
	return s.InodeID
}

// GetName returns the value of Name.
func (s *DirEntry) GetName() OptString {
	return s.Name
}

// GetType returns the value of Type.
func (s *DirEntry) GetType() OptString {
	return s.Type
}

// SetInodeID sets the value of InodeID.
func (s *DirEntry) SetInodeID(val OptString) {
	s.InodeID = val
}

// SetName sets the value of Name.
func (s *DirEntry) SetName(val OptString) {
	s.Name = val
}

// SetType sets the value of Type.
func (s *DirEntry) SetType(val OptString) {
	s.Type = val
}

// Ref: #/components/schemas/DownloadResponse
type DownloadResponse struct {
	Method    string    `json:"method"`
	URL       url.URL   `json:"url"`
	ExpiresAt time.Time `json:"expiresAt"`
}

// GetMethod returns the value of Method.
func (s *DownloadResponse) GetMethod() string {
	return s.Method
}

// GetURL returns the value of URL.
func (s *DownloadResponse) GetURL() url.URL {
	return s.URL
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *DownloadResponse) GetExpiresAt() time.Time {
	return s.ExpiresAt
}

// SetMethod sets the value of Method.
func (s *DownloadResponse) SetMethod(val string) {
	s.Method = val
}

// SetURL sets the value of URL.
func (s *DownloadResponse) SetURL(val url.URL) {
	s.URL = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *DownloadResponse) SetExpiresAt(val time.Time) {
	s.ExpiresAt = val
}

func (*DownloadResponse) presignDownloadRes() {}

// Ref: #/components/schemas/Drive
type Drive struct {
	ID          OptString   `json:"id"`
	PublicID    OptString   `json:"publicID"`
	Name        OptString   `json:"name"`
	Description OptString   `json:"description"`
	OwnerID     OptString   `json:"ownerID"`
	RootNodeID  OptString   `json:"rootNodeID"`
	CreatedAt   OptDateTime `json:"createdAt"`
	UpdatedAt   OptDateTime `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Drive) GetID() OptString {
	return s.ID
}

// GetPublicID returns the value of PublicID.
func (s *Drive) GetPublicID() OptString {
	return s.PublicID
}

// GetName returns the value of Name.
func (s *Drive) GetName() OptString {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Drive) GetDescription() OptString {
	return s.Description
}

// GetOwnerID returns the value of OwnerID.
func (s *Drive) GetOwnerID() OptString {
	return s.OwnerID
}

// GetRootNodeID returns the value of RootNodeID.
func (s *Drive) GetRootNodeID() OptString {
	return s.RootNodeID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Drive) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Drive) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Drive) SetID(val OptString) {
	s.ID = val
}

// SetPublicID sets the value of PublicID.
func (s *Drive) SetPublicID(val OptString) {
	s.PublicID = val
}

// SetName sets the value of Name.
func (s *Drive) SetName(val OptString) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Drive) SetDescription(val OptString) {
	s.Description = val
}

// SetOwnerID sets the value of OwnerID.
func (s *Drive) SetOwnerID(val OptString) {
	s.OwnerID = val
}

// SetRootNodeID sets the value of RootNodeID.
func (s *Drive) SetRootNodeID(val OptString) {
	s.RootNodeID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Drive) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Drive) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

func (*Drive) createDriveRes() {}

// Ref: #/components/schemas/DriveCreate
type DriveCreate struct {
	Name        string        `json:"name"`
	Description OptString     `json:"description"`
	Storage     StorageConfig `json:"storage"`
}

// GetName returns the value of Name.
func (s *DriveCreate) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *DriveCreate) GetDescription() OptString {
	return s.Description
}

// GetStorage returns the value of Storage.
func (s *DriveCreate) GetStorage() StorageConfig {
	return s.Storage
}

// SetName sets the value of Name.
func (s *DriveCreate) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *DriveCreate) SetDescription(val OptString) {
	s.Description = val
}

// SetStorage sets the value of Storage.
func (s *DriveCreate) SetStorage(val StorageConfig) {
	s.Storage = val
}

// Ref: #/components/schemas/DriveUpdate
type DriveUpdate struct {
	Name        OptString `json:"name"`
	Description OptString `json:"description"`
}

// GetName returns the value of Name.
func (s *DriveUpdate) GetName() OptString {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *DriveUpdate) GetDescription() OptString {
	return s.Description
}

// SetName sets the value of Name.
func (s *DriveUpdate) SetName(val OptString) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *DriveUpdate) SetDescription(val OptString) {
	s.Description = val
}

// Ref: #/components/schemas/Error
type Error struct {
	// Machine-readable error code.
	Code ErrorCode `json:"code"`
	// Human-readable error message.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() ErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val ErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// Machine-readable error code.
type ErrorCode string

const (
	ErrorCodeNotFound         ErrorCode = "not_found"
	ErrorCodeConflict         ErrorCode = "conflict"
	ErrorCodeBadRequest       ErrorCode = "bad_request"
	ErrorCodeForbidden        ErrorCode = "forbidden"
	ErrorCodeUnauthorized     ErrorCode = "unauthorized"
	ErrorCodeInternal         ErrorCode = "internal"
	ErrorCodeRevisionConflict ErrorCode = "revision_conflict"
)

// AllValues returns all ErrorCode values.
func (ErrorCode) AllValues() []ErrorCode {
	return []ErrorCode{
		ErrorCodeNotFound,
		ErrorCodeConflict,
		ErrorCodeBadRequest,
		ErrorCodeForbidden,
		ErrorCodeUnauthorized,
		ErrorCodeInternal,
		ErrorCodeRevisionConflict,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ErrorCode) MarshalText() ([]byte, error) {
	switch s {
	case ErrorCodeNotFound:
		return []byte(s), nil
	case ErrorCodeConflict:
		return []byte(s), nil
	case ErrorCodeBadRequest:
		return []byte(s), nil
	case ErrorCodeForbidden:
		return []byte(s), nil
	case ErrorCodeUnauthorized:
		return []byte(s), nil
	case ErrorCodeInternal:
		return []byte(s), nil
	case ErrorCodeRevisionConflict:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ErrorCode) UnmarshalText(data []byte) error {
	switch ErrorCode(data) {
	case ErrorCodeNotFound:
		*s = ErrorCodeNotFound
		return nil
	case ErrorCodeConflict:
		*s = ErrorCodeConflict
		return nil
	case ErrorCodeBadRequest:
		*s = ErrorCodeBadRequest
		return nil
	case ErrorCodeForbidden:
		*s = ErrorCodeForbidden
		return nil
	case ErrorCodeUnauthorized:
		*s = ErrorCodeUnauthorized
		return nil
	case ErrorCodeInternal:
		*s = ErrorCodeInternal
		return nil
	case ErrorCodeRevisionConflict:
		*s = ErrorCodeRevisionConflict
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

func (*ErrorStatusCode) completeUploadRes()  {}
func (*ErrorStatusCode) createDriveRes()     {}
func (*ErrorStatusCode) initiateUploadRes()  {}
func (*ErrorStatusCode) presignDownloadRes() {}
func (*ErrorStatusCode) writeLargeRes()      {}

type HealthOK struct {
	Status OptString `json:"status"`
}

// GetStatus returns the value of Status.
func (s *HealthOK) GetStatus() OptString {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *HealthOK) SetStatus(val OptString) {
	s.Status = val
}

// MkdirCreated is response for Mkdir operation.
type MkdirCreated struct{}

type MkdirReq struct {
	Path string `json:"path"`
}

// GetPath returns the value of Path.
func (s *MkdirReq) GetPath() string {
	return s.Path
}

// SetPath sets the value of Path.
func (s *MkdirReq) SetPath(val string) {
	s.Path = val
}

// MvOK is response for Mv operation.
type MvOK struct{}

type MvReq struct {
	Sources     []string `json:"sources"`
	Destination string   `json:"destination"`
}

// GetSources returns the value of Sources.
func (s *MvReq) GetSources() []string {
	return s.Sources
}

// GetDestination returns the value of Destination.
func (s *MvReq) GetDestination() string {
	return s.Destination
}

// SetSources sets the value of Sources.
func (s *MvReq) SetSources(val []string) {
	s.Sources = val
}

// SetDestination sets the value of Destination.
func (s *MvReq) SetDestination(val string) {
	s.Destination = val
}

// Ref: #/components/schemas/ObjectContent
type ObjectContent struct {
	Bucket      string    `json:"bucket"`
	Key         string    `json:"key"`
	ContentType OptString `json:"contentType"`
	Checksum    OptString `json:"checksum"`
}

// GetBucket returns the value of Bucket.
func (s *ObjectContent) GetBucket() string {
	return s.Bucket
}

// GetKey returns the value of Key.
func (s *ObjectContent) GetKey() string {
	return s.Key
}

// GetContentType returns the value of ContentType.
func (s *ObjectContent) GetContentType() OptString {
	return s.ContentType
}

// GetChecksum returns the value of Checksum.
func (s *ObjectContent) GetChecksum() OptString {
	return s.Checksum
}

// SetBucket sets the value of Bucket.
func (s *ObjectContent) SetBucket(val string) {
	s.Bucket = val
}

// SetKey sets the value of Key.
func (s *ObjectContent) SetKey(val string) {
	s.Key = val
}

// SetContentType sets the value of ContentType.
func (s *ObjectContent) SetContentType(val OptString) {
	s.ContentType = val
}

// SetChecksum sets the value of Checksum.
func (s *ObjectContent) SetChecksum(val OptString) {
	s.Checksum = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDriveCreate returns new OptDriveCreate with value set to v.
func NewOptDriveCreate(v DriveCreate) OptDriveCreate {
	return OptDriveCreate{
		Value: v,
		Set:   true,
	}
}

// OptDriveCreate is optional DriveCreate.
type OptDriveCreate struct {
	Value DriveCreate
	Set   bool
}

// IsSet returns true if OptDriveCreate was set.
func (o OptDriveCreate) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDriveCreate) Reset() {
	var v DriveCreate
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDriveCreate) SetTo(v DriveCreate) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDriveCreate) Get() (v DriveCreate, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDriveCreate) Or(d DriveCreate) DriveCreate {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDriveUpdate returns new OptDriveUpdate with value set to v.
func NewOptDriveUpdate(v DriveUpdate) OptDriveUpdate {
	return OptDriveUpdate{
		Value: v,
		Set:   true,
	}
}

// OptDriveUpdate is optional DriveUpdate.
type OptDriveUpdate struct {
	Value DriveUpdate
	Set   bool
}

// IsSet returns true if OptDriveUpdate was set.
func (o OptDriveUpdate) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDriveUpdate) Reset() {
	var v DriveUpdate
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDriveUpdate) SetTo(v DriveUpdate) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDriveUpdate) Get() (v DriveUpdate, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDriveUpdate) Or(d DriveUpdate) DriveUpdate {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptMkdirReq returns new OptMkdirReq with value set to v.
func NewOptMkdirReq(v MkdirReq) OptMkdirReq {
	return OptMkdirReq{
		Value: v,
		Set:   true,
	}
}

// OptMkdirReq is optional MkdirReq.
type OptMkdirReq struct {
	Value MkdirReq
	Set   bool
}

// IsSet returns true if OptMkdirReq was set.
func (o OptMkdirReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMkdirReq) Reset() {
	var v MkdirReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMkdirReq) SetTo(v MkdirReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMkdirReq) Get() (v MkdirReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMkdirReq) Or(d MkdirReq) MkdirReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptMvReq returns new OptMvReq with value set to v.
func NewOptMvReq(v MvReq) OptMvReq {
	return OptMvReq{
		Value: v,
		Set:   true,
	}
}

// OptMvReq is optional MvReq.
type OptMvReq struct {
	Value MvReq
	Set   bool
}

// IsSet returns true if OptMvReq was set.
func (o OptMvReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMvReq) Reset() {
	var v MvReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMvReq) SetTo(v MvReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMvReq) Get() (v MvReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMvReq) Or(d MvReq) MvReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPresignRequest returns new OptPresignRequest with value set to v.
func NewOptPresignRequest(v PresignRequest) OptPresignRequest {
	return OptPresignRequest{
		Value: v,
		Set:   true,
	}
}

// OptPresignRequest is optional PresignRequest.
type OptPresignRequest struct {
	Value PresignRequest
	Set   bool
}

// IsSet returns true if OptPresignRequest was set.
func (o OptPresignRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPresignRequest) Reset() {
	var v PresignRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPresignRequest) SetTo(v PresignRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPresignRequest) Get() (v PresignRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPresignRequest) Or(d PresignRequest) PresignRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPresignResponseHeaders returns new OptPresignResponseHeaders with value set to v.
func NewOptPresignResponseHeaders(v PresignResponseHeaders) OptPresignResponseHeaders {
	return OptPresignResponseHeaders{
		Value: v,
		Set:   true,
	}
}

// OptPresignResponseHeaders is optional PresignResponseHeaders.
type OptPresignResponseHeaders struct {
	Value PresignResponseHeaders
	Set   bool
}

// IsSet returns true if OptPresignResponseHeaders was set.
func (o OptPresignResponseHeaders) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPresignResponseHeaders) Reset() {
	var v PresignResponseHeaders
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPresignResponseHeaders) SetTo(v PresignResponseHeaders) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPresignResponseHeaders) Get() (v PresignResponseHeaders, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPresignResponseHeaders) Or(d PresignResponseHeaders) PresignResponseHeaders {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptRmReq returns new OptRmReq with value set to v.
func NewOptRmReq(v RmReq) OptRmReq {
	return OptRmReq{
		Value: v,
		Set:   true,
	}
}

// OptRmReq is optional RmReq.
type OptRmReq struct {
	Value RmReq
	Set   bool
}

// IsSet returns true if OptRmReq was set.
func (o OptRmReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptRmReq) Reset() {
	var v RmReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptRmReq) SetTo(v RmReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptRmReq) Get() (v RmReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptRmReq) Or(d RmReq) RmReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSymlinkReq returns new OptSymlinkReq with value set to v.
func NewOptSymlinkReq(v SymlinkReq) OptSymlinkReq {
	return OptSymlinkReq{
		Value: v,
		Set:   true,
	}
}

// OptSymlinkReq is optional SymlinkReq.
type OptSymlinkReq struct {
	Value SymlinkReq
	Set   bool
}

// IsSet returns true if OptSymlinkReq was set.
func (o OptSymlinkReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSymlinkReq) Reset() {
	var v SymlinkReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSymlinkReq) SetTo(v SymlinkReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSymlinkReq) Get() (v SymlinkReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSymlinkReq) Or(d SymlinkReq) SymlinkReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTouchReq returns new OptTouchReq with value set to v.
func NewOptTouchReq(v TouchReq) OptTouchReq {
	return OptTouchReq{
		Value: v,
		Set:   true,
	}
}

// OptTouchReq is optional TouchReq.
type OptTouchReq struct {
	Value TouchReq
	Set   bool
}

// IsSet returns true if OptTouchReq was set.
func (o OptTouchReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTouchReq) Reset() {
	var v TouchReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTouchReq) SetTo(v TouchReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTouchReq) Get() (v TouchReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTouchReq) Or(d TouchReq) TouchReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUploadCompleteRequest returns new OptUploadCompleteRequest with value set to v.
func NewOptUploadCompleteRequest(v UploadCompleteRequest) OptUploadCompleteRequest {
	return OptUploadCompleteRequest{
		Value: v,
		Set:   true,
	}
}

// OptUploadCompleteRequest is optional UploadCompleteRequest.
type OptUploadCompleteRequest struct {
	Value UploadCompleteRequest
	Set   bool
}

// IsSet returns true if OptUploadCompleteRequest was set.
func (o OptUploadCompleteRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUploadCompleteRequest) Reset() {
	var v UploadCompleteRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUploadCompleteRequest) SetTo(v UploadCompleteRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUploadCompleteRequest) Get() (v UploadCompleteRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUploadCompleteRequest) Or(d UploadCompleteRequest) UploadCompleteRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpsertUserReq returns new OptUpsertUserReq with value set to v.
func NewOptUpsertUserReq(v UpsertUserReq) OptUpsertUserReq {
	return OptUpsertUserReq{
		Value: v,
		Set:   true,
	}
}

// OptUpsertUserReq is optional UpsertUserReq.
type OptUpsertUserReq struct {
	Value UpsertUserReq
	Set   bool
}

// IsSet returns true if OptUpsertUserReq was set.
func (o OptUpsertUserReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpsertUserReq) Reset() {
	var v UpsertUserReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpsertUserReq) SetTo(v UpsertUserReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpsertUserReq) Get() (v UpsertUserReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpsertUserReq) Or(d UpsertUserReq) UpsertUserReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptWriteLargeReq returns new OptWriteLargeReq with value set to v.
func NewOptWriteLargeReq(v WriteLargeReq) OptWriteLargeReq {
	return OptWriteLargeReq{
		Value: v,
		Set:   true,
	}
}

// OptWriteLargeReq is optional WriteLargeReq.
type OptWriteLargeReq struct {
	Value WriteLargeReq
	Set   bool
}

// IsSet returns true if OptWriteLargeReq was set.
func (o OptWriteLargeReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptWriteLargeReq) Reset() {
	var v WriteLargeReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptWriteLargeReq) SetTo(v WriteLargeReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptWriteLargeReq) Get() (v WriteLargeReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptWriteLargeReq) Or(d WriteLargeReq) WriteLargeReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptWriteReq returns new OptWriteReq with value set to v.
func NewOptWriteReq(v WriteReq) OptWriteReq {
	return OptWriteReq{
		Value: v,
		Set:   true,
	}
}

// OptWriteReq is optional WriteReq.
type OptWriteReq struct {
	Value WriteReq
	Set   bool
}

// IsSet returns true if OptWriteReq was set.
func (o OptWriteReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptWriteReq) Reset() {
	var v WriteReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptWriteReq) SetTo(v WriteReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptWriteReq) Get() (v WriteReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptWriteReq) Or(d WriteReq) WriteReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PresignRequest
type PresignRequest struct {
	// Destination path inside the drive.
	Path string `json:"path"`
	// MIME type of the object (optional, included in the signed URL).
	ContentType OptString `json:"contentType"`
	// Expected object size in bytes (optional).
	ContentLength OptInt64 `json:"contentLength"`
}

// GetPath returns the value of Path.
func (s *PresignRequest) GetPath() string {
	return s.Path
}

// GetContentType returns the value of ContentType.
func (s *PresignRequest) GetContentType() OptString {
	return s.ContentType
}

// GetContentLength returns the value of ContentLength.
func (s *PresignRequest) GetContentLength() OptInt64 {
	return s.ContentLength
}

// SetPath sets the value of Path.
func (s *PresignRequest) SetPath(val string) {
	s.Path = val
}

// SetContentType sets the value of ContentType.
func (s *PresignRequest) SetContentType(val OptString) {
	s.ContentType = val
}

// SetContentLength sets the value of ContentLength.
func (s *PresignRequest) SetContentLength(val OptInt64) {
	s.ContentLength = val
}

// Ref: #/components/schemas/PresignResponse
type PresignResponse struct {
	// Opaque token to pass to the complete endpoint.
	UploadId string `json:"uploadId"`
	Method   string `json:"method"`
	// Presigned URL the client PUTs the bytes to.
	URL url.URL `json:"url"`
	// Headers that must be included with the PUT request.
	Headers OptPresignResponseHeaders `json:"headers"`
	// S3 object key that will be created.
	Key       string    `json:"key"`
	ExpiresAt time.Time `json:"expiresAt"`
}

// GetUploadId returns the value of UploadId.
func (s *PresignResponse) GetUploadId() string {
	return s.UploadId
}

// GetMethod returns the value of Method.
func (s *PresignResponse) GetMethod() string {
	return s.Method
}

// GetURL returns the value of URL.
func (s *PresignResponse) GetURL() url.URL {
	return s.URL
}

// GetHeaders returns the value of Headers.
func (s *PresignResponse) GetHeaders() OptPresignResponseHeaders {
	return s.Headers
}

// GetKey returns the value of Key.
func (s *PresignResponse) GetKey() string {
	return s.Key
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *PresignResponse) GetExpiresAt() time.Time {
	return s.ExpiresAt
}

// SetUploadId sets the value of UploadId.
func (s *PresignResponse) SetUploadId(val string) {
	s.UploadId = val
}

// SetMethod sets the value of Method.
func (s *PresignResponse) SetMethod(val string) {
	s.Method = val
}

// SetURL sets the value of URL.
func (s *PresignResponse) SetURL(val url.URL) {
	s.URL = val
}

// SetHeaders sets the value of Headers.
func (s *PresignResponse) SetHeaders(val OptPresignResponseHeaders) {
	s.Headers = val
}

// SetKey sets the value of Key.
func (s *PresignResponse) SetKey(val string) {
	s.Key = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *PresignResponse) SetExpiresAt(val time.Time) {
	s.ExpiresAt = val
}

func (*PresignResponse) initiateUploadRes() {}

// Headers that must be included with the PUT request.
type PresignResponseHeaders map[string]string

func (s *PresignResponseHeaders) init() PresignResponseHeaders {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// RmNoContent is response for Rm operation.
type RmNoContent struct{}

type RmReq struct {
	Paths     []string `json:"paths"`
	Recursive OptBool  `json:"recursive"`
}

// GetPaths returns the value of Paths.
func (s *RmReq) GetPaths() []string {
	return s.Paths
}

// GetRecursive returns the value of Recursive.
func (s *RmReq) GetRecursive() OptBool {
	return s.Recursive
}

// SetPaths sets the value of Paths.
func (s *RmReq) SetPaths(val []string) {
	s.Paths = val
}

// SetRecursive sets the value of Recursive.
func (s *RmReq) SetRecursive(val OptBool) {
	s.Recursive = val
}

type StatOK struct {
	Type     OptString   `json:"type"`
	Size     OptInt64    `json:"size"`
	Atime    OptDateTime `json:"atime"`
	Mtime    OptDateTime `json:"mtime"`
	Ctime    OptDateTime `json:"ctime"`
	Flags    OptString   `json:"flags"`
	Revision OptString   `json:"revision"`
}

// GetType returns the value of Type.
func (s *StatOK) GetType() OptString {
	return s.Type
}

// GetSize returns the value of Size.
func (s *StatOK) GetSize() OptInt64 {
	return s.Size
}

// GetAtime returns the value of Atime.
func (s *StatOK) GetAtime() OptDateTime {
	return s.Atime
}

// GetMtime returns the value of Mtime.
func (s *StatOK) GetMtime() OptDateTime {
	return s.Mtime
}

// GetCtime returns the value of Ctime.
func (s *StatOK) GetCtime() OptDateTime {
	return s.Ctime
}

// GetFlags returns the value of Flags.
func (s *StatOK) GetFlags() OptString {
	return s.Flags
}

// GetRevision returns the value of Revision.
func (s *StatOK) GetRevision() OptString {
	return s.Revision
}

// SetType sets the value of Type.
func (s *StatOK) SetType(val OptString) {
	s.Type = val
}

// SetSize sets the value of Size.
func (s *StatOK) SetSize(val OptInt64) {
	s.Size = val
}

// SetAtime sets the value of Atime.
func (s *StatOK) SetAtime(val OptDateTime) {
	s.Atime = val
}

// SetMtime sets the value of Mtime.
func (s *StatOK) SetMtime(val OptDateTime) {
	s.Mtime = val
}

// SetCtime sets the value of Ctime.
func (s *StatOK) SetCtime(val OptDateTime) {
	s.Ctime = val
}

// SetFlags sets the value of Flags.
func (s *StatOK) SetFlags(val OptString) {
	s.Flags = val
}

// SetRevision sets the value of Revision.
func (s *StatOK) SetRevision(val OptString) {
	s.Revision = val
}

// Ref: #/components/schemas/StorageConfig
type StorageConfig struct {
	Bucket       string    `json:"bucket"`
	Endpoint     OptString `json:"endpoint"`
	Region       string    `json:"region"`
	AccessKey    string    `json:"accessKey"`
	SecretKey    string    `json:"secretKey"`
	UsePathStyle OptBool   `json:"usePathStyle"`
}

// GetBucket returns the value of Bucket.
func (s *StorageConfig) GetBucket() string {
	return s.Bucket
}

// GetEndpoint returns the value of Endpoint.
func (s *StorageConfig) GetEndpoint() OptString {
	return s.Endpoint
}

// GetRegion returns the value of Region.
func (s *StorageConfig) GetRegion() string {
	return s.Region
}

// GetAccessKey returns the value of AccessKey.
func (s *StorageConfig) GetAccessKey() string {
	return s.AccessKey
}

// GetSecretKey returns the value of SecretKey.
func (s *StorageConfig) GetSecretKey() string {
	return s.SecretKey
}

// GetUsePathStyle returns the value of UsePathStyle.
func (s *StorageConfig) GetUsePathStyle() OptBool {
	return s.UsePathStyle
}

// SetBucket sets the value of Bucket.
func (s *StorageConfig) SetBucket(val string) {
	s.Bucket = val
}

// SetEndpoint sets the value of Endpoint.
func (s *StorageConfig) SetEndpoint(val OptString) {
	s.Endpoint = val
}

// SetRegion sets the value of Region.
func (s *StorageConfig) SetRegion(val string) {
	s.Region = val
}

// SetAccessKey sets the value of AccessKey.
func (s *StorageConfig) SetAccessKey(val string) {
	s.AccessKey = val
}

// SetSecretKey sets the value of SecretKey.
func (s *StorageConfig) SetSecretKey(val string) {
	s.SecretKey = val
}

// SetUsePathStyle sets the value of UsePathStyle.
func (s *StorageConfig) SetUsePathStyle(val OptBool) {
	s.UsePathStyle = val
}

// SymlinkCreated is response for Symlink operation.
type SymlinkCreated struct{}

type SymlinkReq struct {
	Target   string `json:"target"`
	LinkPath string `json:"linkPath"`
}

// GetTarget returns the value of Target.
func (s *SymlinkReq) GetTarget() string {
	return s.Target
}

// GetLinkPath returns the value of LinkPath.
func (s *SymlinkReq) GetLinkPath() string {
	return s.LinkPath
}

// SetTarget sets the value of Target.
func (s *SymlinkReq) SetTarget(val string) {
	s.Target = val
}

// SetLinkPath sets the value of LinkPath.
func (s *SymlinkReq) SetLinkPath(val string) {
	s.LinkPath = val
}

// TouchCreated is response for Touch operation.
type TouchCreated struct{}

type TouchReq struct {
	Path string `json:"path"`
}

// GetPath returns the value of Path.
func (s *TouchReq) GetPath() string {
	return s.Path
}

// SetPath sets the value of Path.
func (s *TouchReq) SetPath(val string) {
	s.Path = val
}

// Ref: #/components/schemas/UploadCompleteRequest
type UploadCompleteRequest struct {
	// Actual object size in bytes.
	ContentLength int64 `json:"contentLength"`
	// ETag or checksum of the uploaded object (optional).
	Checksum OptString `json:"checksum"`
}

// GetContentLength returns the value of ContentLength.
func (s *UploadCompleteRequest) GetContentLength() int64 {
	return s.ContentLength
}

// GetChecksum returns the value of Checksum.
func (s *UploadCompleteRequest) GetChecksum() OptString {
	return s.Checksum
}

// SetContentLength sets the value of ContentLength.
func (s *UploadCompleteRequest) SetContentLength(val int64) {
	s.ContentLength = val
}

// SetChecksum sets the value of Checksum.
func (s *UploadCompleteRequest) SetChecksum(val OptString) {
	s.Checksum = val
}

// Ref: #/components/schemas/UploadCompleteResponse
type UploadCompleteResponse struct {
	InodeID string      `json:"inodeID"`
	Size    int64       `json:"size"`
	Mtime   OptDateTime `json:"mtime"`
	Atime   OptDateTime `json:"atime"`
}

// GetInodeID returns the value of InodeID.
func (s *UploadCompleteResponse) GetInodeID() string {
	return s.InodeID
}

// GetSize returns the value of Size.
func (s *UploadCompleteResponse) GetSize() int64 {
	return s.Size
}

// GetMtime returns the value of Mtime.
func (s *UploadCompleteResponse) GetMtime() OptDateTime {
	return s.Mtime
}

// GetAtime returns the value of Atime.
func (s *UploadCompleteResponse) GetAtime() OptDateTime {
	return s.Atime
}

// SetInodeID sets the value of InodeID.
func (s *UploadCompleteResponse) SetInodeID(val string) {
	s.InodeID = val
}

// SetSize sets the value of Size.
func (s *UploadCompleteResponse) SetSize(val int64) {
	s.Size = val
}

// SetMtime sets the value of Mtime.
func (s *UploadCompleteResponse) SetMtime(val OptDateTime) {
	s.Mtime = val
}

// SetAtime sets the value of Atime.
func (s *UploadCompleteResponse) SetAtime(val OptDateTime) {
	s.Atime = val
}

func (*UploadCompleteResponse) completeUploadRes() {}

// UpsertUserOK is response for UpsertUser operation.
type UpsertUserOK struct{}

type UpsertUserReq struct {
	Name       string    `json:"name"`
	Email      OptString `json:"email"`
	Provider   string    `json:"provider"`
	ProviderID string    `json:"providerID"`
}

// GetName returns the value of Name.
func (s *UpsertUserReq) GetName() string {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *UpsertUserReq) GetEmail() OptString {
	return s.Email
}

// GetProvider returns the value of Provider.
func (s *UpsertUserReq) GetProvider() string {
	return s.Provider
}

// GetProviderID returns the value of ProviderID.
func (s *UpsertUserReq) GetProviderID() string {
	return s.ProviderID
}

// SetName sets the value of Name.
func (s *UpsertUserReq) SetName(val string) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *UpsertUserReq) SetEmail(val OptString) {
	s.Email = val
}

// SetProvider sets the value of Provider.
func (s *UpsertUserReq) SetProvider(val string) {
	s.Provider = val
}

// SetProviderID sets the value of ProviderID.
func (s *UpsertUserReq) SetProviderID(val string) {
	s.ProviderID = val
}

// Ref: #/components/schemas/User
type User struct {
	ID         OptString   `json:"id"`
	PublicID   OptString   `json:"publicID"`
	Name       OptString   `json:"name"`
	Email      OptString   `json:"email"`
	Provider   OptString   `json:"provider"`
	ProviderID OptString   `json:"providerID"`
	CreatedAt  OptDateTime `json:"createdAt"`
	UpdatedAt  OptDateTime `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *User) GetID() OptString {
	return s.ID
}

// GetPublicID returns the value of PublicID.
func (s *User) GetPublicID() OptString {
	return s.PublicID
}

// GetName returns the value of Name.
func (s *User) GetName() OptString {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *User) GetEmail() OptString {
	return s.Email
}

// GetProvider returns the value of Provider.
func (s *User) GetProvider() OptString {
	return s.Provider
}

// GetProviderID returns the value of ProviderID.
func (s *User) GetProviderID() OptString {
	return s.ProviderID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *User) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *User) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *User) SetID(val OptString) {
	s.ID = val
}

// SetPublicID sets the value of PublicID.
func (s *User) SetPublicID(val OptString) {
	s.PublicID = val
}

// SetName sets the value of Name.
func (s *User) SetName(val OptString) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *User) SetEmail(val OptString) {
	s.Email = val
}

// SetProvider sets the value of Provider.
func (s *User) SetProvider(val OptString) {
	s.Provider = val
}

// SetProviderID sets the value of ProviderID.
func (s *User) SetProviderID(val OptString) {
	s.ProviderID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *User) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *User) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

// WriteLargeCreated is response for WriteLarge operation.
type WriteLargeCreated struct{}

func (*WriteLargeCreated) writeLargeRes() {}

type WriteLargeReq struct {
	Path   string        `json:"path"`
	Size   int64         `json:"size"`
	Object ObjectContent `json:"object"`
}

// GetPath returns the value of Path.
func (s *WriteLargeReq) GetPath() string {
	return s.Path
}

// GetSize returns the value of Size.
func (s *WriteLargeReq) GetSize() int64 {
	return s.Size
}

// GetObject returns the value of Object.
func (s *WriteLargeReq) GetObject() ObjectContent {
	return s.Object
}

// SetPath sets the value of Path.
func (s *WriteLargeReq) SetPath(val string) {
	s.Path = val
}

// SetSize sets the value of Size.
func (s *WriteLargeReq) SetSize(val int64) {
	s.Size = val
}

// SetObject sets the value of Object.
func (s *WriteLargeReq) SetObject(val ObjectContent) {
	s.Object = val
}

// WriteOK is response for Write operation.
type WriteOK struct{}

type WriteReq struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}

// GetPath returns the value of Path.
func (s *WriteReq) GetPath() string {
	return s.Path
}

// GetContent returns the value of Content.
func (s *WriteReq) GetContent() string {
	return s.Content
}

// SetPath sets the value of Path.
func (s *WriteReq) SetPath(val string) {
	s.Path = val
}

// SetContent sets the value of Content.
func (s *WriteReq) SetContent(val string) {
	s.Content = val
}
