// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package nodeMocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/mandacode-labs/mdrive/internal/core/node"
	mock "github.com/stretchr/testify/mock"
)

// NewLinkerMock creates a new instance of LinkerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkerMock {
	mock := &LinkerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LinkerMock is an autogenerated mock type for the Linker type
type LinkerMock struct {
	mock.Mock
}

type LinkerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LinkerMock) EXPECT() *LinkerMock_Expecter {
	return &LinkerMock_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type LinkerMock
func (_mock *LinkerMock) GetByID(ctx context.Context, id uuid.UUID) (*node.Node, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *node.Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*node.Node, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *node.Node); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*node.Node)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LinkerMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type LinkerMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *LinkerMock_Expecter) GetByID(ctx interface{}, id interface{}) *LinkerMock_GetByID_Call {
	return &LinkerMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *LinkerMock_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *LinkerMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LinkerMock_GetByID_Call) Return(node1 *node.Node, err error) *LinkerMock_GetByID_Call {
	_c.Call.Return(node1, err)
	return _c
}

func (_c *LinkerMock_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*node.Node, error)) *LinkerMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Link provides a mock function for the type LinkerMock
func (_mock *LinkerMock) Link(ctx context.Context, parent *node.Node, name string, child *node.Node) error {
	ret := _mock.Called(ctx, parent, name, child)

	if len(ret) == 0 {
		panic("no return value specified for Link")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *node.Node, string, *node.Node) error); ok {
		r0 = returnFunc(ctx, parent, name, child)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LinkerMock_Link_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Link'
type LinkerMock_Link_Call struct {
	*mock.Call
}

// Link is a helper method to define mock.On call
//   - ctx context.Context
//   - parent *node.Node
//   - name string
//   - child *node.Node
func (_e *LinkerMock_Expecter) Link(ctx interface{}, parent interface{}, name interface{}, child interface{}) *LinkerMock_Link_Call {
	return &LinkerMock_Link_Call{Call: _e.mock.On("Link", ctx, parent, name, child)}
}

func (_c *LinkerMock_Link_Call) Run(run func(ctx context.Context, parent *node.Node, name string, child *node.Node)) *LinkerMock_Link_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *node.Node
		if args[1] != nil {
			arg1 = args[1].(*node.Node)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *node.Node
		if args[3] != nil {
			arg3 = args[3].(*node.Node)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *LinkerMock_Link_Call) Return(err error) *LinkerMock_Link_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LinkerMock_Link_Call) RunAndReturn(run func(ctx context.Context, parent *node.Node, name string, child *node.Node) error) *LinkerMock_Link_Call {
	_c.Call.Return(run)
	return _c
}

// MoveEntry provides a mock function for the type LinkerMock
func (_mock *LinkerMock) MoveEntry(ctx context.Context, srcParent *node.Node, srcName string, dstParent *node.Node, dstName string) error {
	ret := _mock.Called(ctx, srcParent, srcName, dstParent, dstName)

	if len(ret) == 0 {
		panic("no return value specified for MoveEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *node.Node, string, *node.Node, string) error); ok {
		r0 = returnFunc(ctx, srcParent, srcName, dstParent, dstName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LinkerMock_MoveEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MoveEntry'
type LinkerMock_MoveEntry_Call struct {
	*mock.Call
}

// MoveEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - srcParent *node.Node
//   - srcName string
//   - dstParent *node.Node
//   - dstName string
func (_e *LinkerMock_Expecter) MoveEntry(ctx interface{}, srcParent interface{}, srcName interface{}, dstParent interface{}, dstName interface{}) *LinkerMock_MoveEntry_Call {
	return &LinkerMock_MoveEntry_Call{Call: _e.mock.On("MoveEntry", ctx, srcParent, srcName, dstParent, dstName)}
}

func (_c *LinkerMock_MoveEntry_Call) Run(run func(ctx context.Context, srcParent *node.Node, srcName string, dstParent *node.Node, dstName string)) *LinkerMock_MoveEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *node.Node
		if args[1] != nil {
			arg1 = args[1].(*node.Node)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *node.Node
		if args[3] != nil {
			arg3 = args[3].(*node.Node)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *LinkerMock_MoveEntry_Call) Return(err error) *LinkerMock_MoveEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LinkerMock_MoveEntry_Call) RunAndReturn(run func(ctx context.Context, srcParent *node.Node, srcName string, dstParent *node.Node, dstName string) error) *LinkerMock_MoveEntry_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type LinkerMock
func (_mock *LinkerMock) Save(ctx context.Context, n *node.Node) error {
	ret := _mock.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *node.Node) error); ok {
		r0 = returnFunc(ctx, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LinkerMock_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type LinkerMock_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - n *node.Node
func (_e *LinkerMock_Expecter) Save(ctx interface{}, n interface{}) *LinkerMock_Save_Call {
	return &LinkerMock_Save_Call{Call: _e.mock.On("Save", ctx, n)}
}

func (_c *LinkerMock_Save_Call) Run(run func(ctx context.Context, n *node.Node)) *LinkerMock_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *node.Node
		if args[1] != nil {
			arg1 = args[1].(*node.Node)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LinkerMock_Save_Call) Return(err error) *LinkerMock_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LinkerMock_Save_Call) RunAndReturn(run func(ctx context.Context, n *node.Node) error) *LinkerMock_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Unlink provides a mock function for the type LinkerMock
func (_mock *LinkerMock) Unlink(ctx context.Context, parent *node.Node, name string) (*node.Node, error) {
	ret := _mock.Called(ctx, parent, name)

	if len(ret) == 0 {
		panic("no return value specified for Unlink")
	}

	var r0 *node.Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *node.Node, string) (*node.Node, error)); ok {
		return returnFunc(ctx, parent, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *node.Node, string) *node.Node); ok {
		r0 = returnFunc(ctx, parent, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*node.Node)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *node.Node, string) error); ok {
		r1 = returnFunc(ctx, parent, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LinkerMock_Unlink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlink'
type LinkerMock_Unlink_Call struct {
	*mock.Call
}

// Unlink is a helper method to define mock.On call
//   - ctx context.Context
//   - parent *node.Node
//   - name string
func (_e *LinkerMock_Expecter) Unlink(ctx interface{}, parent interface{}, name interface{}) *LinkerMock_Unlink_Call {
	return &LinkerMock_Unlink_Call{Call: _e.mock.On("Unlink", ctx, parent, name)}
}

func (_c *LinkerMock_Unlink_Call) Run(run func(ctx context.Context, parent *node.Node, name string)) *LinkerMock_Unlink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *node.Node
		if args[1] != nil {
			arg1 = args[1].(*node.Node)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LinkerMock_Unlink_Call) Return(node1 *node.Node, err error) *LinkerMock_Unlink_Call {
	_c.Call.Return(node1, err)
	return _c
}

func (_c *LinkerMock_Unlink_Call) RunAndReturn(run func(ctx context.Context, parent *node.Node, name string) (*node.Node, error)) *LinkerMock_Unlink_Call {
	_c.Call.Return(run)
	return _c
}
