// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AuthCallback implements authCallback operation.
	//
	// OAuth callback from Zitadel.
	//
	// GET /auth/callback
	AuthCallback(ctx context.Context, params AuthCallbackParams) (AuthCallbackRes, error)
	// AuthLogout implements authLogout operation.
	//
	// Destroy the current session.
	//
	// POST /auth/logout
	AuthLogout(ctx context.Context) (AuthLogoutRes, error)
	// AuthMe implements authMe operation.
	//
	// Get the current authenticated user.
	//
	// GET /auth/me
	AuthMe(ctx context.Context) (AuthMeRes, error)
	// Cat implements cat operation.
	//
	// Read file contents (POSIX open(O_RDONLY)).
	//
	// GET /v1/drives/{driveID}/fs/cat
	Cat(ctx context.Context, params CatParams) (CatRes, error)
	// CompleteUpload implements completeUpload operation.
	//
	// Complete a presigned upload and create the object node.
	//
	// POST /v1/drives/{driveID}/uploads/{uploadId}/complete
	CompleteUpload(ctx context.Context, req OptUploadCompleteRequest, params CompleteUploadParams) (CompleteUploadRes, error)
	// CreateDrive implements createDrive operation.
	//
	// Create a new drive.
	//
	// POST /v1/drives
	CreateDrive(ctx context.Context, req OptDriveCreate) (CreateDriveRes, error)
	// DeleteDrive implements deleteDrive operation.
	//
	// Soft-delete a drive.
	//
	// DELETE /v1/drives/{driveID}/root
	DeleteDrive(ctx context.Context, params DeleteDriveParams) (DeleteDriveRes, error)
	// GetDrive implements getDrive operation.
	//
	// Get a drive by ID.
	//
	// GET /v1/drives/{driveID}/root
	GetDrive(ctx context.Context, params GetDriveParams) (GetDriveRes, error)
	// GetDriveStorage implements getDriveStorage operation.
	//
	// Get a drive's storage configuration.
	//
	// GET /v1/drives/{driveID}/storage
	GetDriveStorage(ctx context.Context, params GetDriveStorageParams) (GetDriveStorageRes, error)
	// GetUser implements getUser operation.
	//
	// Get current user.
	//
	// GET /v1/users
	GetUser(ctx context.Context) (GetUserRes, error)
	// GoogleLogin implements googleLogin operation.
	//
	// Initiate Google OAuth login (web).
	//
	// GET /auth/google
	GoogleLogin(ctx context.Context) (*GoogleLoginFound, error)
	// GoogleNativeLogin implements googleNativeLogin operation.
	//
	// Exchange a Google id_token for a mdrive session (mobile).
	//
	// POST /auth/google/native
	GoogleNativeLogin(ctx context.Context, req OptGoogleNativeLoginReq) (GoogleNativeLoginRes, error)
	// Hardlink implements hardlink operation.
	//
	// Create a hard link (POSIX link(2)).
	//
	// POST /v1/drives/{driveID}/fs/hardlink
	Hardlink(ctx context.Context, req OptHardlinkReq, params HardlinkParams) (HardlinkRes, error)
	// Health implements health operation.
	//
	// Health check.
	//
	// GET /health
	Health(ctx context.Context) (*HealthOK, error)
	// InitiateUpload implements initiateUpload operation.
	//
	// Initiate a presigned upload.
	//
	// POST /v1/drives/{driveID}/uploads
	InitiateUpload(ctx context.Context, req OptPresignRequest, params InitiateUploadParams) (InitiateUploadRes, error)
	// ListDeletedDrives implements listDeletedDrives operation.
	//
	// List soft-deleted drives (admin only).
	//
	// GET /v1/admin/drives/deleted
	ListDeletedDrives(ctx context.Context) (ListDeletedDrivesRes, error)
	// ListDrives implements listDrives operation.
	//
	// List drives owned by the authenticated user.
	//
	// GET /v1/drives
	ListDrives(ctx context.Context) (ListDrivesRes, error)
	// Ls implements ls operation.
	//
	// List directory contents (POSIX opendir/readdir).
	//
	// GET /v1/drives/{driveID}/fs/ls
	Ls(ctx context.Context, params LsParams) (LsRes, error)
	// Lstat implements lstat operation.
	//
	// Get file metadata without following symlinks (POSIX lstat(2)).
	//
	// GET /v1/drives/{driveID}/fs/lstat
	Lstat(ctx context.Context, params LstatParams) (LstatRes, error)
	// Mkdir implements mkdir operation.
	//
	// Create a directory (POSIX mkdir(2)).
	//
	// POST /v1/drives/{driveID}/fs/mkdir
	Mkdir(ctx context.Context, req OptMkdirReq, params MkdirParams) (MkdirRes, error)
	// Mount implements mount operation.
	//
	// Bind-mount another drive at a path (POSIX mount-like).
	//
	// POST /v1/drives/{driveID}/fs/mount
	Mount(ctx context.Context, req OptMountReq, params MountParams) (MountRes, error)
	// Mv implements mv operation.
	//
	// Move files or directories (POSIX rename(2)).
	//
	// POST /v1/drives/{driveID}/fs/mv
	Mv(ctx context.Context, req OptMvReq, params MvParams) (MvRes, error)
	// PresignDownload implements presignDownload operation.
	//
	// Get a presigned download URL for an object node.
	//
	// GET /v1/drives/{driveID}/downloads
	PresignDownload(ctx context.Context, params PresignDownloadParams) (PresignDownloadRes, error)
	// Readlink implements readlink operation.
	//
	// Read a symbolic link's target (POSIX readlink(2)).
	//
	// GET /v1/drives/{driveID}/fs/readlink
	Readlink(ctx context.Context, params ReadlinkParams) (ReadlinkRes, error)
	// Realpath implements realpath operation.
	//
	// Resolve all symlinks and return the canonical (driveID, path) pair (POSIX realpath(3)).
	//
	// GET /v1/drives/{driveID}/fs/realpath
	Realpath(ctx context.Context, params RealpathParams) (RealpathRes, error)
	// RestoreDrive implements restoreDrive operation.
	//
	// Restore a soft-deleted drive.
	//
	// POST /v1/drives/{driveID}/restore
	RestoreDrive(ctx context.Context, params RestoreDriveParams) (RestoreDriveRes, error)
	// Rm implements rm operation.
	//
	// Remove files or directories (POSIX unlink/rmdir(2)).
	//
	// DELETE /v1/drives/{driveID}/fs
	Rm(ctx context.Context, req OptRmReq, params RmParams) (RmRes, error)
	// Stat implements stat operation.
	//
	// Get file metadata, following symlinks (POSIX stat(2)).
	//
	// GET /v1/drives/{driveID}/fs/stat
	Stat(ctx context.Context, params StatParams) (StatRes, error)
	// Symlink implements symlink operation.
	//
	// Create a symbolic link (POSIX symlink(2)).
	//
	// POST /v1/drives/{driveID}/fs/symlink
	Symlink(ctx context.Context, req OptSymlinkReq, params SymlinkParams) (SymlinkRes, error)
	// Touch implements touch operation.
	//
	// Create an empty file (POSIX open(O_CREAT)).
	//
	// POST /v1/drives/{driveID}/fs/touch
	Touch(ctx context.Context, req OptTouchReq, params TouchParams) (TouchRes, error)
	// Unmount implements unmount operation.
	//
	// Remove a bind mount (POSIX umount-like).
	//
	// DELETE /v1/drives/{driveID}/fs/unmount
	Unmount(ctx context.Context, params UnmountParams) (UnmountRes, error)
	// UpdateDrive implements updateDrive operation.
	//
	// Update a drive.
	//
	// PUT /v1/drives/{driveID}/root
	UpdateDrive(ctx context.Context, req OptDriveUpdate, params UpdateDriveParams) (UpdateDriveRes, error)
	// UpsertUser implements upsertUser operation.
	//
	// Upsert a user from OIDC claims.
	//
	// POST /v1/users
	UpsertUser(ctx context.Context, req OptUpsertUserReq) (UpsertUserRes, error)
	// Write implements write operation.
	//
	// Write inline content to a file.
	//
	// PUT /v1/drives/{driveID}/fs/write
	Write(ctx context.Context, req OptWriteReq, params WriteParams) (WriteRes, error)
	// WriteLarge implements writeLarge operation.
	//
	// Create an S3-backed object node.
	//
	// POST /v1/drives/{driveID}/fs/object
	WriteLarge(ctx context.Context, req OptWriteLargeReq, params WriteLargeParams) (WriteLargeRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
