// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AuthCallback implements authCallback operation.
//
// OAuth callback from Zitadel.
//
// GET /auth/callback
func (UnimplementedHandler) AuthCallback(ctx context.Context, params AuthCallbackParams) error {
	return ht.ErrNotImplemented
}

// AuthLogout implements authLogout operation.
//
// Destroy the current session.
//
// POST /auth/logout
func (UnimplementedHandler) AuthLogout(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// AuthMe implements authMe operation.
//
// Get the current authenticated user.
//
// GET /auth/me
func (UnimplementedHandler) AuthMe(ctx context.Context) (r *User, _ error) {
	return r, ht.ErrNotImplemented
}

// Cat implements cat operation.
//
// Read file contents (POSIX open(O_RDONLY)).
//
// GET /v1/drives/{driveID}/fs/cat
func (UnimplementedHandler) Cat(ctx context.Context, params CatParams) (r CatRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CompleteUpload implements completeUpload operation.
//
// Complete a presigned upload and create the object node.
//
// POST /v1/drives/{driveID}/uploads/{uploadId}/complete
func (UnimplementedHandler) CompleteUpload(ctx context.Context, req OptUploadCompleteRequest, params CompleteUploadParams) (r CompleteUploadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDrive implements createDrive operation.
//
// Create a new drive.
//
// POST /v1/drives
func (UnimplementedHandler) CreateDrive(ctx context.Context, req OptDriveCreate) (r CreateDriveRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDrive implements deleteDrive operation.
//
// Soft-delete a drive.
//
// DELETE /v1/drives/{driveID}/root
func (UnimplementedHandler) DeleteDrive(ctx context.Context, params DeleteDriveParams) error {
	return ht.ErrNotImplemented
}

// GetDrive implements getDrive operation.
//
// Get a drive by ID.
//
// GET /v1/drives/{driveID}/root
func (UnimplementedHandler) GetDrive(ctx context.Context, params GetDriveParams) (r *Drive, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDriveStorage implements getDriveStorage operation.
//
// Get a drive's storage configuration.
//
// GET /v1/drives/{driveID}/storage
func (UnimplementedHandler) GetDriveStorage(ctx context.Context, params GetDriveStorageParams) (r *StorageConfig, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUser implements getUser operation.
//
// Get current user.
//
// GET /v1/users
func (UnimplementedHandler) GetUser(ctx context.Context) (r *User, _ error) {
	return r, ht.ErrNotImplemented
}

// GoogleLogin implements googleLogin operation.
//
// Initiate Google OAuth login (web).
//
// GET /auth/google
func (UnimplementedHandler) GoogleLogin(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// GoogleNativeLogin implements googleNativeLogin operation.
//
// Exchange a Google id_token for a mdrive session (mobile).
//
// POST /auth/google/native
func (UnimplementedHandler) GoogleNativeLogin(ctx context.Context, req OptGoogleNativeLoginReq) (r *GoogleNativeLoginOK, _ error) {
	return r, ht.ErrNotImplemented
}

// Hardlink implements hardlink operation.
//
// Create a hard link (POSIX link(2)).
//
// POST /v1/drives/{driveID}/fs/hardlink
func (UnimplementedHandler) Hardlink(ctx context.Context, req OptHardlinkReq, params HardlinkParams) (r HardlinkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Health implements health operation.
//
// Health check.
//
// GET /health
func (UnimplementedHandler) Health(ctx context.Context) (r *HealthOK, _ error) {
	return r, ht.ErrNotImplemented
}

// InitiateUpload implements initiateUpload operation.
//
// Initiate a presigned upload.
//
// POST /v1/drives/{driveID}/uploads
func (UnimplementedHandler) InitiateUpload(ctx context.Context, req OptPresignRequest, params InitiateUploadParams) (r InitiateUploadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDeletedDrives implements listDeletedDrives operation.
//
// List soft-deleted drives (admin only).
//
// GET /v1/admin/drives/deleted
func (UnimplementedHandler) ListDeletedDrives(ctx context.Context) (r []Drive, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDrives implements listDrives operation.
//
// List drives owned by the authenticated user.
//
// GET /v1/drives
func (UnimplementedHandler) ListDrives(ctx context.Context) (r []Drive, _ error) {
	return r, ht.ErrNotImplemented
}

// Ls implements ls operation.
//
// List directory contents (POSIX opendir/readdir).
//
// GET /v1/drives/{driveID}/fs/ls
func (UnimplementedHandler) Ls(ctx context.Context, params LsParams) (r LsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Lstat implements lstat operation.
//
// Get file metadata without following symlinks (POSIX lstat(2)).
//
// GET /v1/drives/{driveID}/fs/lstat
func (UnimplementedHandler) Lstat(ctx context.Context, params LstatParams) (r LstatRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Mkdir implements mkdir operation.
//
// Create a directory (POSIX mkdir(2)).
//
// POST /v1/drives/{driveID}/fs/mkdir
func (UnimplementedHandler) Mkdir(ctx context.Context, req OptMkdirReq, params MkdirParams) (r MkdirRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Mount implements mount operation.
//
// Bind-mount another drive at a path (POSIX mount-like).
//
// POST /v1/drives/{driveID}/fs/mount
func (UnimplementedHandler) Mount(ctx context.Context, req OptMountReq, params MountParams) (r MountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Mv implements mv operation.
//
// Move files or directories (POSIX rename(2)).
//
// POST /v1/drives/{driveID}/fs/mv
func (UnimplementedHandler) Mv(ctx context.Context, req OptMvReq, params MvParams) (r MvRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PresignDownload implements presignDownload operation.
//
// Get a presigned download URL for an object node.
//
// GET /v1/drives/{driveID}/downloads
func (UnimplementedHandler) PresignDownload(ctx context.Context, params PresignDownloadParams) (r PresignDownloadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Readlink implements readlink operation.
//
// Read a symbolic link's target (POSIX readlink(2)).
//
// GET /v1/drives/{driveID}/fs/readlink
func (UnimplementedHandler) Readlink(ctx context.Context, params ReadlinkParams) (r ReadlinkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Realpath implements realpath operation.
//
// Resolve all symlinks and return the canonical (driveID, path) pair (POSIX realpath(3)).
//
// GET /v1/drives/{driveID}/fs/realpath
func (UnimplementedHandler) Realpath(ctx context.Context, params RealpathParams) (r RealpathRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RestoreDrive implements restoreDrive operation.
//
// Restore a soft-deleted drive.
//
// POST /v1/drives/{driveID}/restore
func (UnimplementedHandler) RestoreDrive(ctx context.Context, params RestoreDriveParams) (r *Drive, _ error) {
	return r, ht.ErrNotImplemented
}

// Rm implements rm operation.
//
// Remove files or directories (POSIX unlink/rmdir(2)).
//
// DELETE /v1/drives/{driveID}/fs
func (UnimplementedHandler) Rm(ctx context.Context, req OptRmReq, params RmParams) (r RmRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Stat implements stat operation.
//
// Get file metadata, following symlinks (POSIX stat(2)).
//
// GET /v1/drives/{driveID}/fs/stat
func (UnimplementedHandler) Stat(ctx context.Context, params StatParams) (r StatRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Symlink implements symlink operation.
//
// Create a symbolic link (POSIX symlink(2)).
//
// POST /v1/drives/{driveID}/fs/symlink
func (UnimplementedHandler) Symlink(ctx context.Context, req OptSymlinkReq, params SymlinkParams) (r SymlinkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Touch implements touch operation.
//
// Create an empty file (POSIX open(O_CREAT)).
//
// POST /v1/drives/{driveID}/fs/touch
func (UnimplementedHandler) Touch(ctx context.Context, req OptTouchReq, params TouchParams) (r TouchRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Unmount implements unmount operation.
//
// Remove a bind mount (POSIX umount-like).
//
// DELETE /v1/drives/{driveID}/fs/unmount
func (UnimplementedHandler) Unmount(ctx context.Context, params UnmountParams) (r UnmountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDrive implements updateDrive operation.
//
// Update a drive.
//
// PUT /v1/drives/{driveID}/root
func (UnimplementedHandler) UpdateDrive(ctx context.Context, req OptDriveUpdate, params UpdateDriveParams) (r *Drive, _ error) {
	return r, ht.ErrNotImplemented
}

// UpsertUser implements upsertUser operation.
//
// Upsert a user from OIDC claims.
//
// POST /v1/users
func (UnimplementedHandler) UpsertUser(ctx context.Context, req OptUpsertUserReq) error {
	return ht.ErrNotImplemented
}

// Write implements write operation.
//
// Write inline content to a file.
//
// PUT /v1/drives/{driveID}/fs/write
func (UnimplementedHandler) Write(ctx context.Context, req OptWriteReq, params WriteParams) (r WriteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WriteLarge implements writeLarge operation.
//
// Create an S3-backed object node.
//
// POST /v1/drives/{driveID}/fs/object
func (UnimplementedHandler) WriteLarge(ctx context.Context, req OptWriteLargeReq, params WriteLargeParams) (r WriteLargeRes, _ error) {
	return r, ht.ErrNotImplemented
}
