// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn4AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn13AllowedHeaders = map[string]string{
		"DELETE": "Authorization,Content-Type",
	}
	rn3AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn9AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn10AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn12AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn19AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn14AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn16AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn17AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn18AllowedHeaders = map[string]string{
		"PUT": "Authorization,Content-Type",
	}
	rn6AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"GET":    "Authorization",
		"PUT":    "Authorization,Content-Type",
	}
	rn7AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [1]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/v1/drives"

			if l := len("/v1/drives"); len(elem) >= l && elem[0:l] == "/v1/drives" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				switch r.Method {
				case "GET":
					s.handleListDrivesRequest([0]string{}, elemIsEscaped, w, r)
				case "POST":
					s.handleCreateDriveRequest([0]string{}, elemIsEscaped, w, r)
				default:
					s.notAllowed(w, r, notAllowedParams{
						allowedMethods: "GET,POST",
						allowedHeaders: rn4AllowedHeaders,
						acceptPost:     "application/json",
						acceptPatch:    "",
					})
				}

				return
			}
			switch elem[0] {
			case '/': // Prefix: "/"

				if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
					elem = elem[l:]
				} else {
					break
				}

				// Param: "driveID"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[0] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'f': // Prefix: "fs"

						if l := len("fs"); len(elem) >= l && elem[0:l] == "fs" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "DELETE":
								s.handleRmRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE",
									allowedHeaders: rn13AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'c': // Prefix: "cat"

								if l := len("cat"); len(elem) >= l && elem[0:l] == "cat" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleCatRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn3AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							case 'l': // Prefix: "ls"

								if l := len("ls"); len(elem) >= l && elem[0:l] == "ls" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleLsRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn9AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							case 'm': // Prefix: "m"

								if l := len("m"); len(elem) >= l && elem[0:l] == "m" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'k': // Prefix: "kdir"

									if l := len("kdir"); len(elem) >= l && elem[0:l] == "kdir" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleMkdirRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn10AllowedHeaders,
												acceptPost:     "application/json",
												acceptPatch:    "",
											})
										}

										return
									}

								case 'v': // Prefix: "v"

									if l := len("v"); len(elem) >= l && elem[0:l] == "v" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleMvRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn12AllowedHeaders,
												acceptPost:     "application/json",
												acceptPatch:    "",
											})
										}

										return
									}

								}

							case 'o': // Prefix: "object"

								if l := len("object"); len(elem) >= l && elem[0:l] == "object" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleWriteLargeRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn19AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							case 's': // Prefix: "s"

								if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 't': // Prefix: "tat"

									if l := len("tat"); len(elem) >= l && elem[0:l] == "tat" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "GET":
											s.handleStatRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "GET",
												allowedHeaders: rn14AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}

								case 'y': // Prefix: "ymlink"

									if l := len("ymlink"); len(elem) >= l && elem[0:l] == "ymlink" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleSymlinkRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn16AllowedHeaders,
												acceptPost:     "application/json",
												acceptPatch:    "",
											})
										}

										return
									}

								}

							case 't': // Prefix: "touch"

								if l := len("touch"); len(elem) >= l && elem[0:l] == "touch" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleTouchRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn17AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							case 'w': // Prefix: "write"

								if l := len("write"); len(elem) >= l && elem[0:l] == "write" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "PUT":
										s.handleWriteRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "PUT",
											allowedHeaders: rn18AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						}

					case 'r': // Prefix: "root"

						if l := len("root"); len(elem) >= l && elem[0:l] == "root" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "DELETE":
								s.handleDeleteDriveRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "GET":
								s.handleGetDriveRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "PUT":
								s.handleUpdateDriveRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "DELETE,GET,PUT",
									allowedHeaders: rn6AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 's': // Prefix: "storage"

						if l := len("storage"); len(elem) >= l && elem[0:l] == "storage" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetDriveStorageRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn7AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [1]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/v1/drives"

			if l := len("/v1/drives"); len(elem) >= l && elem[0:l] == "/v1/drives" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				switch method {
				case "GET":
					r.name = ListDrivesOperation
					r.summary = "List drives owned by the authenticated user"
					r.operationID = "listDrives"
					r.operationGroup = ""
					r.pathPattern = "/v1/drives"
					r.args = args
					r.count = 0
					return r, true
				case "POST":
					r.name = CreateDriveOperation
					r.summary = "Create a new drive"
					r.operationID = "createDrive"
					r.operationGroup = ""
					r.pathPattern = "/v1/drives"
					r.args = args
					r.count = 0
					return r, true
				default:
					return
				}
			}
			switch elem[0] {
			case '/': // Prefix: "/"

				if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
					elem = elem[l:]
				} else {
					break
				}

				// Param: "driveID"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[0] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'f': // Prefix: "fs"

						if l := len("fs"); len(elem) >= l && elem[0:l] == "fs" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "DELETE":
								r.name = RmOperation
								r.summary = "Remove files or directories"
								r.operationID = "rm"
								r.operationGroup = ""
								r.pathPattern = "/v1/drives/{driveID}/fs"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'c': // Prefix: "cat"

								if l := len("cat"); len(elem) >= l && elem[0:l] == "cat" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = CatOperation
										r.summary = "Read file contents"
										r.operationID = "cat"
										r.operationGroup = ""
										r.pathPattern = "/v1/drives/{driveID}/fs/cat"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 'l': // Prefix: "ls"

								if l := len("ls"); len(elem) >= l && elem[0:l] == "ls" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = LsOperation
										r.summary = "List directory contents"
										r.operationID = "ls"
										r.operationGroup = ""
										r.pathPattern = "/v1/drives/{driveID}/fs/ls"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 'm': // Prefix: "m"

								if l := len("m"); len(elem) >= l && elem[0:l] == "m" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'k': // Prefix: "kdir"

									if l := len("kdir"); len(elem) >= l && elem[0:l] == "kdir" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = MkdirOperation
											r.summary = "Create a directory"
											r.operationID = "mkdir"
											r.operationGroup = ""
											r.pathPattern = "/v1/drives/{driveID}/fs/mkdir"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

								case 'v': // Prefix: "v"

									if l := len("v"); len(elem) >= l && elem[0:l] == "v" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = MvOperation
											r.summary = "Move files or directories"
											r.operationID = "mv"
											r.operationGroup = ""
											r.pathPattern = "/v1/drives/{driveID}/fs/mv"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

								}

							case 'o': // Prefix: "object"

								if l := len("object"); len(elem) >= l && elem[0:l] == "object" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = WriteLargeOperation
										r.summary = "Create an S3-backed object node"
										r.operationID = "writeLarge"
										r.operationGroup = ""
										r.pathPattern = "/v1/drives/{driveID}/fs/object"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 's': // Prefix: "s"

								if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 't': // Prefix: "tat"

									if l := len("tat"); len(elem) >= l && elem[0:l] == "tat" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "GET":
											r.name = StatOperation
											r.summary = "Get file metadata"
											r.operationID = "stat"
											r.operationGroup = ""
											r.pathPattern = "/v1/drives/{driveID}/fs/stat"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

								case 'y': // Prefix: "ymlink"

									if l := len("ymlink"); len(elem) >= l && elem[0:l] == "ymlink" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = SymlinkOperation
											r.summary = "Create a symbolic link"
											r.operationID = "symlink"
											r.operationGroup = ""
											r.pathPattern = "/v1/drives/{driveID}/fs/symlink"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

								}

							case 't': // Prefix: "touch"

								if l := len("touch"); len(elem) >= l && elem[0:l] == "touch" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = TouchOperation
										r.summary = "Create an empty file"
										r.operationID = "touch"
										r.operationGroup = ""
										r.pathPattern = "/v1/drives/{driveID}/fs/touch"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 'w': // Prefix: "write"

								if l := len("write"); len(elem) >= l && elem[0:l] == "write" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "PUT":
										r.name = WriteOperation
										r.summary = "Write inline content to a file"
										r.operationID = "write"
										r.operationGroup = ""
										r.pathPattern = "/v1/drives/{driveID}/fs/write"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						}

					case 'r': // Prefix: "root"

						if l := len("root"); len(elem) >= l && elem[0:l] == "root" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "DELETE":
								r.name = DeleteDriveOperation
								r.summary = "Delete a drive and all its nodes"
								r.operationID = "deleteDrive"
								r.operationGroup = ""
								r.pathPattern = "/v1/drives/{driveID}/root"
								r.args = args
								r.count = 1
								return r, true
							case "GET":
								r.name = GetDriveOperation
								r.summary = "Get a drive by ID"
								r.operationID = "getDrive"
								r.operationGroup = ""
								r.pathPattern = "/v1/drives/{driveID}/root"
								r.args = args
								r.count = 1
								return r, true
							case "PUT":
								r.name = UpdateDriveOperation
								r.summary = "Update a drive"
								r.operationID = "updateDrive"
								r.operationGroup = ""
								r.pathPattern = "/v1/drives/{driveID}/root"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					case 's': // Prefix: "storage"

						if l := len("storage"); len(elem) >= l && elem[0:l] == "storage" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GetDriveStorageOperation
								r.summary = "Get a drive's storage configuration"
								r.operationID = "getDriveStorage"
								r.operationGroup = ""
								r.pathPattern = "/v1/drives/{driveID}/storage"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			}

		}
	}
	return r, false
}
