// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package vfsMocks

import (
	mock "github.com/stretchr/testify/mock"
)

// newInodeGetterMock creates a new instance of inodeGetterMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newInodeGetterMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *inodeGetterMock {
	mock := &inodeGetterMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// inodeGetterMock is an autogenerated mock type for the inodeGetter type
type inodeGetterMock struct {
	mock.Mock
}

type inodeGetterMock_Expecter struct {
	mock *mock.Mock
}

func (_m *inodeGetterMock) EXPECT() *inodeGetterMock_Expecter {
	return &inodeGetterMock_Expecter{mock: &_m.Mock}
}

// ObjectID provides a mock function for the type inodeGetterMock
func (_mock *inodeGetterMock) ObjectID() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ObjectID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// inodeGetterMock_ObjectID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObjectID'
type inodeGetterMock_ObjectID_Call struct {
	*mock.Call
}

// ObjectID is a helper method to define mock.On call
func (_e *inodeGetterMock_Expecter) ObjectID() *inodeGetterMock_ObjectID_Call {
	return &inodeGetterMock_ObjectID_Call{Call: _e.mock.On("ObjectID")}
}

func (_c *inodeGetterMock_ObjectID_Call) Run(run func()) *inodeGetterMock_ObjectID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *inodeGetterMock_ObjectID_Call) Return(s string, err error) *inodeGetterMock_ObjectID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *inodeGetterMock_ObjectID_Call) RunAndReturn(run func() (string, error)) *inodeGetterMock_ObjectID_Call {
	_c.Call.Return(run)
	return _c
}
