// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlerMocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// newRequestProviderMock creates a new instance of requestProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newRequestProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *requestProviderMock {
	mock := &requestProviderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// requestProviderMock is an autogenerated mock type for the requestProvider type
type requestProviderMock struct {
	mock.Mock
}

type requestProviderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *requestProviderMock) EXPECT() *requestProviderMock_Expecter {
	return &requestProviderMock_Expecter{mock: &_m.Mock}
}

// Request provides a mock function for the type requestProviderMock
func (_mock *requestProviderMock) Request() *http.Request {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 *http.Request
	if returnFunc, ok := ret.Get(0).(func() *http.Request); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}
	return r0
}

// requestProviderMock_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type requestProviderMock_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
func (_e *requestProviderMock_Expecter) Request() *requestProviderMock_Request_Call {
	return &requestProviderMock_Request_Call{Call: _e.mock.On("Request")}
}

func (_c *requestProviderMock_Request_Call) Run(run func()) *requestProviderMock_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *requestProviderMock_Request_Call) Return(request *http.Request) *requestProviderMock_Request_Call {
	_c.Call.Return(request)
	return _c
}

func (_c *requestProviderMock_Request_Call) RunAndReturn(run func() *http.Request) *requestProviderMock_Request_Call {
	_c.Call.Return(run)
	return _c
}
