// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlerMocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/mandacode-labs/mdrive/internal/core/drive"
	"github.com/mandacode-labs/mdrive/internal/core/node"
	"github.com/mandacode-labs/mdrive/internal/core/user"
	"github.com/mandacode-labs/mdrive/internal/vfs"
	mock "github.com/stretchr/testify/mock"
)

// NewFSClientMock creates a new instance of FSClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFSClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FSClientMock {
	mock := &FSClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FSClientMock is an autogenerated mock type for the FSClient type
type FSClientMock struct {
	mock.Mock
}

type FSClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *FSClientMock) EXPECT() *FSClientMock_Expecter {
	return &FSClientMock_Expecter{mock: &_m.Mock}
}

// Cat provides a mock function for the type FSClientMock
func (_mock *FSClientMock) Cat(ctx context.Context, userID string, driveID string, path string) ([]byte, error) {
	ret := _mock.Called(ctx, userID, driveID, path)

	if len(ret) == 0 {
		panic("no return value specified for Cat")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]byte, error)); ok {
		return returnFunc(ctx, userID, driveID, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []byte); ok {
		r0 = returnFunc(ctx, userID, driveID, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, driveID, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FSClientMock_Cat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cat'
type FSClientMock_Cat_Call struct {
	*mock.Call
}

// Cat is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - driveID string
//   - path string
func (_e *FSClientMock_Expecter) Cat(ctx interface{}, userID interface{}, driveID interface{}, path interface{}) *FSClientMock_Cat_Call {
	return &FSClientMock_Cat_Call{Call: _e.mock.On("Cat", ctx, userID, driveID, path)}
}

func (_c *FSClientMock_Cat_Call) Run(run func(ctx context.Context, userID string, driveID string, path string)) *FSClientMock_Cat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *FSClientMock_Cat_Call) Return(bytes []byte, err error) *FSClientMock_Cat_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *FSClientMock_Cat_Call) RunAndReturn(run func(ctx context.Context, userID string, driveID string, path string) ([]byte, error)) *FSClientMock_Cat_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteUpload provides a mock function for the type FSClientMock
func (_mock *FSClientMock) CompleteUpload(ctx context.Context, userID string, driveID string, uploadID string, contentLength int64, checksum *string) (*node.Node, error) {
	ret := _mock.Called(ctx, userID, driveID, uploadID, contentLength, checksum)

	if len(ret) == 0 {
		panic("no return value specified for CompleteUpload")
	}

	var r0 *node.Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64, *string) (*node.Node, error)); ok {
		return returnFunc(ctx, userID, driveID, uploadID, contentLength, checksum)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64, *string) *node.Node); ok {
		r0 = returnFunc(ctx, userID, driveID, uploadID, contentLength, checksum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*node.Node)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, int64, *string) error); ok {
		r1 = returnFunc(ctx, userID, driveID, uploadID, contentLength, checksum)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FSClientMock_CompleteUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteUpload'
type FSClientMock_CompleteUpload_Call struct {
	*mock.Call
}

// CompleteUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - driveID string
//   - uploadID string
//   - contentLength int64
//   - checksum *string
func (_e *FSClientMock_Expecter) CompleteUpload(ctx interface{}, userID interface{}, driveID interface{}, uploadID interface{}, contentLength interface{}, checksum interface{}) *FSClientMock_CompleteUpload_Call {
	return &FSClientMock_CompleteUpload_Call{Call: _e.mock.On("CompleteUpload", ctx, userID, driveID, uploadID, contentLength, checksum)}
}

func (_c *FSClientMock_CompleteUpload_Call) Run(run func(ctx context.Context, userID string, driveID string, uploadID string, contentLength int64, checksum *string)) *FSClientMock_CompleteUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 *string
		if args[5] != nil {
			arg5 = args[5].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *FSClientMock_CompleteUpload_Call) Return(node1 *node.Node, err error) *FSClientMock_CompleteUpload_Call {
	_c.Call.Return(node1, err)
	return _c
}

func (_c *FSClientMock_CompleteUpload_Call) RunAndReturn(run func(ctx context.Context, userID string, driveID string, uploadID string, contentLength int64, checksum *string) (*node.Node, error)) *FSClientMock_CompleteUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDrive provides a mock function for the type FSClientMock
func (_mock *FSClientMock) CreateDrive(ctx context.Context, actorID string, name string, description string, cfg drive.StorageConfig) (*drive.Drive, uuid.UUID, error) {
	ret := _mock.Called(ctx, actorID, name, description, cfg)

	if len(ret) == 0 {
		panic("no return value specified for CreateDrive")
	}

	var r0 *drive.Drive
	var r1 uuid.UUID
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, drive.StorageConfig) (*drive.Drive, uuid.UUID, error)); ok {
		return returnFunc(ctx, actorID, name, description, cfg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, drive.StorageConfig) *drive.Drive); ok {
		r0 = returnFunc(ctx, actorID, name, description, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*drive.Drive)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, drive.StorageConfig) uuid.UUID); ok {
		r1 = returnFunc(ctx, actorID, name, description, cfg)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string, drive.StorageConfig) error); ok {
		r2 = returnFunc(ctx, actorID, name, description, cfg)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// FSClientMock_CreateDrive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDrive'
type FSClientMock_CreateDrive_Call struct {
	*mock.Call
}

// CreateDrive is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - name string
//   - description string
//   - cfg drive.StorageConfig
func (_e *FSClientMock_Expecter) CreateDrive(ctx interface{}, actorID interface{}, name interface{}, description interface{}, cfg interface{}) *FSClientMock_CreateDrive_Call {
	return &FSClientMock_CreateDrive_Call{Call: _e.mock.On("CreateDrive", ctx, actorID, name, description, cfg)}
}

func (_c *FSClientMock_CreateDrive_Call) Run(run func(ctx context.Context, actorID string, name string, description string, cfg drive.StorageConfig)) *FSClientMock_CreateDrive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 drive.StorageConfig
		if args[4] != nil {
			arg4 = args[4].(drive.StorageConfig)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *FSClientMock_CreateDrive_Call) Return(drive1 *drive.Drive, uUID uuid.UUID, err error) *FSClientMock_CreateDrive_Call {
	_c.Call.Return(drive1, uUID, err)
	return _c
}

func (_c *FSClientMock_CreateDrive_Call) RunAndReturn(run func(ctx context.Context, actorID string, name string, description string, cfg drive.StorageConfig) (*drive.Drive, uuid.UUID, error)) *FSClientMock_CreateDrive_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDrive provides a mock function for the type FSClientMock
func (_mock *FSClientMock) DeleteDrive(ctx context.Context, actorID string, id string) error {
	ret := _mock.Called(ctx, actorID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDrive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, actorID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FSClientMock_DeleteDrive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDrive'
type FSClientMock_DeleteDrive_Call struct {
	*mock.Call
}

// DeleteDrive is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - id string
func (_e *FSClientMock_Expecter) DeleteDrive(ctx interface{}, actorID interface{}, id interface{}) *FSClientMock_DeleteDrive_Call {
	return &FSClientMock_DeleteDrive_Call{Call: _e.mock.On("DeleteDrive", ctx, actorID, id)}
}

func (_c *FSClientMock_DeleteDrive_Call) Run(run func(ctx context.Context, actorID string, id string)) *FSClientMock_DeleteDrive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FSClientMock_DeleteDrive_Call) Return(err error) *FSClientMock_DeleteDrive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FSClientMock_DeleteDrive_Call) RunAndReturn(run func(ctx context.Context, actorID string, id string) error) *FSClientMock_DeleteDrive_Call {
	_c.Call.Return(run)
	return _c
}

// GetDrive provides a mock function for the type FSClientMock
func (_mock *FSClientMock) GetDrive(ctx context.Context, actorID string, id string) (*drive.Drive, error) {
	ret := _mock.Called(ctx, actorID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDrive")
	}

	var r0 *drive.Drive
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*drive.Drive, error)); ok {
		return returnFunc(ctx, actorID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *drive.Drive); ok {
		r0 = returnFunc(ctx, actorID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*drive.Drive)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, actorID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FSClientMock_GetDrive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDrive'
type FSClientMock_GetDrive_Call struct {
	*mock.Call
}

// GetDrive is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - id string
func (_e *FSClientMock_Expecter) GetDrive(ctx interface{}, actorID interface{}, id interface{}) *FSClientMock_GetDrive_Call {
	return &FSClientMock_GetDrive_Call{Call: _e.mock.On("GetDrive", ctx, actorID, id)}
}

func (_c *FSClientMock_GetDrive_Call) Run(run func(ctx context.Context, actorID string, id string)) *FSClientMock_GetDrive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FSClientMock_GetDrive_Call) Return(drive1 *drive.Drive, err error) *FSClientMock_GetDrive_Call {
	_c.Call.Return(drive1, err)
	return _c
}

func (_c *FSClientMock_GetDrive_Call) RunAndReturn(run func(ctx context.Context, actorID string, id string) (*drive.Drive, error)) *FSClientMock_GetDrive_Call {
	_c.Call.Return(run)
	return _c
}

// GetDriveStorage provides a mock function for the type FSClientMock
func (_mock *FSClientMock) GetDriveStorage(ctx context.Context, actorID string, driveID string) (*drive.Storage, error) {
	ret := _mock.Called(ctx, actorID, driveID)

	if len(ret) == 0 {
		panic("no return value specified for GetDriveStorage")
	}

	var r0 *drive.Storage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*drive.Storage, error)); ok {
		return returnFunc(ctx, actorID, driveID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *drive.Storage); ok {
		r0 = returnFunc(ctx, actorID, driveID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*drive.Storage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, actorID, driveID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FSClientMock_GetDriveStorage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDriveStorage'
type FSClientMock_GetDriveStorage_Call struct {
	*mock.Call
}

// GetDriveStorage is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - driveID string
func (_e *FSClientMock_Expecter) GetDriveStorage(ctx interface{}, actorID interface{}, driveID interface{}) *FSClientMock_GetDriveStorage_Call {
	return &FSClientMock_GetDriveStorage_Call{Call: _e.mock.On("GetDriveStorage", ctx, actorID, driveID)}
}

func (_c *FSClientMock_GetDriveStorage_Call) Run(run func(ctx context.Context, actorID string, driveID string)) *FSClientMock_GetDriveStorage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FSClientMock_GetDriveStorage_Call) Return(storage *drive.Storage, err error) *FSClientMock_GetDriveStorage_Call {
	_c.Call.Return(storage, err)
	return _c
}

func (_c *FSClientMock_GetDriveStorage_Call) RunAndReturn(run func(ctx context.Context, actorID string, driveID string) (*drive.Storage, error)) *FSClientMock_GetDriveStorage_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type FSClientMock
func (_mock *FSClientMock) GetUser(ctx context.Context, actorID string, id string) (*user.User, error) {
	ret := _mock.Called(ctx, actorID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*user.User, error)); ok {
		return returnFunc(ctx, actorID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *user.User); ok {
		r0 = returnFunc(ctx, actorID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, actorID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FSClientMock_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type FSClientMock_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - id string
func (_e *FSClientMock_Expecter) GetUser(ctx interface{}, actorID interface{}, id interface{}) *FSClientMock_GetUser_Call {
	return &FSClientMock_GetUser_Call{Call: _e.mock.On("GetUser", ctx, actorID, id)}
}

func (_c *FSClientMock_GetUser_Call) Run(run func(ctx context.Context, actorID string, id string)) *FSClientMock_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FSClientMock_GetUser_Call) Return(user1 *user.User, err error) *FSClientMock_GetUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *FSClientMock_GetUser_Call) RunAndReturn(run func(ctx context.Context, actorID string, id string) (*user.User, error)) *FSClientMock_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// InitiateUpload provides a mock function for the type FSClientMock
func (_mock *FSClientMock) InitiateUpload(ctx context.Context, userID string, driveID string, destPath string, contentType *string, contentLength *int64, expiry time.Duration) (vfs.PresignInfo, error) {
	ret := _mock.Called(ctx, userID, driveID, destPath, contentType, contentLength, expiry)

	if len(ret) == 0 {
		panic("no return value specified for InitiateUpload")
	}

	var r0 vfs.PresignInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *string, *int64, time.Duration) (vfs.PresignInfo, error)); ok {
		return returnFunc(ctx, userID, driveID, destPath, contentType, contentLength, expiry)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *string, *int64, time.Duration) vfs.PresignInfo); ok {
		r0 = returnFunc(ctx, userID, driveID, destPath, contentType, contentLength, expiry)
	} else {
		r0 = ret.Get(0).(vfs.PresignInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, *string, *int64, time.Duration) error); ok {
		r1 = returnFunc(ctx, userID, driveID, destPath, contentType, contentLength, expiry)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FSClientMock_InitiateUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitiateUpload'
type FSClientMock_InitiateUpload_Call struct {
	*mock.Call
}

// InitiateUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - driveID string
//   - destPath string
//   - contentType *string
//   - contentLength *int64
//   - expiry time.Duration
func (_e *FSClientMock_Expecter) InitiateUpload(ctx interface{}, userID interface{}, driveID interface{}, destPath interface{}, contentType interface{}, contentLength interface{}, expiry interface{}) *FSClientMock_InitiateUpload_Call {
	return &FSClientMock_InitiateUpload_Call{Call: _e.mock.On("InitiateUpload", ctx, userID, driveID, destPath, contentType, contentLength, expiry)}
}

func (_c *FSClientMock_InitiateUpload_Call) Run(run func(ctx context.Context, userID string, driveID string, destPath string, contentType *string, contentLength *int64, expiry time.Duration)) *FSClientMock_InitiateUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		var arg5 *int64
		if args[5] != nil {
			arg5 = args[5].(*int64)
		}
		var arg6 time.Duration
		if args[6] != nil {
			arg6 = args[6].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *FSClientMock_InitiateUpload_Call) Return(presignInfo vfs.PresignInfo, err error) *FSClientMock_InitiateUpload_Call {
	_c.Call.Return(presignInfo, err)
	return _c
}

func (_c *FSClientMock_InitiateUpload_Call) RunAndReturn(run func(ctx context.Context, userID string, driveID string, destPath string, contentType *string, contentLength *int64, expiry time.Duration) (vfs.PresignInfo, error)) *FSClientMock_InitiateUpload_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserDrives provides a mock function for the type FSClientMock
func (_mock *FSClientMock) ListUserDrives(ctx context.Context, actorID string) ([]*drive.Drive, error) {
	ret := _mock.Called(ctx, actorID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserDrives")
	}

	var r0 []*drive.Drive
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*drive.Drive, error)); ok {
		return returnFunc(ctx, actorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*drive.Drive); ok {
		r0 = returnFunc(ctx, actorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*drive.Drive)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, actorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FSClientMock_ListUserDrives_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserDrives'
type FSClientMock_ListUserDrives_Call struct {
	*mock.Call
}

// ListUserDrives is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
func (_e *FSClientMock_Expecter) ListUserDrives(ctx interface{}, actorID interface{}) *FSClientMock_ListUserDrives_Call {
	return &FSClientMock_ListUserDrives_Call{Call: _e.mock.On("ListUserDrives", ctx, actorID)}
}

func (_c *FSClientMock_ListUserDrives_Call) Run(run func(ctx context.Context, actorID string)) *FSClientMock_ListUserDrives_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FSClientMock_ListUserDrives_Call) Return(drives []*drive.Drive, err error) *FSClientMock_ListUserDrives_Call {
	_c.Call.Return(drives, err)
	return _c
}

func (_c *FSClientMock_ListUserDrives_Call) RunAndReturn(run func(ctx context.Context, actorID string) ([]*drive.Drive, error)) *FSClientMock_ListUserDrives_Call {
	_c.Call.Return(run)
	return _c
}

// Ls provides a mock function for the type FSClientMock
func (_mock *FSClientMock) Ls(ctx context.Context, userID string, driveID string, path string) (node.DirContent, error) {
	ret := _mock.Called(ctx, userID, driveID, path)

	if len(ret) == 0 {
		panic("no return value specified for Ls")
	}

	var r0 node.DirContent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (node.DirContent, error)); ok {
		return returnFunc(ctx, userID, driveID, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) node.DirContent); ok {
		r0 = returnFunc(ctx, userID, driveID, path)
	} else {
		r0 = ret.Get(0).(node.DirContent)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, driveID, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FSClientMock_Ls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ls'
type FSClientMock_Ls_Call struct {
	*mock.Call
}

// Ls is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - driveID string
//   - path string
func (_e *FSClientMock_Expecter) Ls(ctx interface{}, userID interface{}, driveID interface{}, path interface{}) *FSClientMock_Ls_Call {
	return &FSClientMock_Ls_Call{Call: _e.mock.On("Ls", ctx, userID, driveID, path)}
}

func (_c *FSClientMock_Ls_Call) Run(run func(ctx context.Context, userID string, driveID string, path string)) *FSClientMock_Ls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *FSClientMock_Ls_Call) Return(dirContent node.DirContent, err error) *FSClientMock_Ls_Call {
	_c.Call.Return(dirContent, err)
	return _c
}

func (_c *FSClientMock_Ls_Call) RunAndReturn(run func(ctx context.Context, userID string, driveID string, path string) (node.DirContent, error)) *FSClientMock_Ls_Call {
	_c.Call.Return(run)
	return _c
}

// Mkdir provides a mock function for the type FSClientMock
func (_mock *FSClientMock) Mkdir(ctx context.Context, userID string, driveID string, path string) (*node.Node, error) {
	ret := _mock.Called(ctx, userID, driveID, path)

	if len(ret) == 0 {
		panic("no return value specified for Mkdir")
	}

	var r0 *node.Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*node.Node, error)); ok {
		return returnFunc(ctx, userID, driveID, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *node.Node); ok {
		r0 = returnFunc(ctx, userID, driveID, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*node.Node)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, driveID, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FSClientMock_Mkdir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mkdir'
type FSClientMock_Mkdir_Call struct {
	*mock.Call
}

// Mkdir is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - driveID string
//   - path string
func (_e *FSClientMock_Expecter) Mkdir(ctx interface{}, userID interface{}, driveID interface{}, path interface{}) *FSClientMock_Mkdir_Call {
	return &FSClientMock_Mkdir_Call{Call: _e.mock.On("Mkdir", ctx, userID, driveID, path)}
}

func (_c *FSClientMock_Mkdir_Call) Run(run func(ctx context.Context, userID string, driveID string, path string)) *FSClientMock_Mkdir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *FSClientMock_Mkdir_Call) Return(node1 *node.Node, err error) *FSClientMock_Mkdir_Call {
	_c.Call.Return(node1, err)
	return _c
}

func (_c *FSClientMock_Mkdir_Call) RunAndReturn(run func(ctx context.Context, userID string, driveID string, path string) (*node.Node, error)) *FSClientMock_Mkdir_Call {
	_c.Call.Return(run)
	return _c
}

// Mv provides a mock function for the type FSClientMock
func (_mock *FSClientMock) Mv(ctx context.Context, userID string, srcDriveID string, srcPaths []string, dstDriveID string, dstPath string) error {
	ret := _mock.Called(ctx, userID, srcDriveID, srcPaths, dstDriveID, dstPath)

	if len(ret) == 0 {
		panic("no return value specified for Mv")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string, string, string) error); ok {
		r0 = returnFunc(ctx, userID, srcDriveID, srcPaths, dstDriveID, dstPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FSClientMock_Mv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mv'
type FSClientMock_Mv_Call struct {
	*mock.Call
}

// Mv is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - srcDriveID string
//   - srcPaths []string
//   - dstDriveID string
//   - dstPath string
func (_e *FSClientMock_Expecter) Mv(ctx interface{}, userID interface{}, srcDriveID interface{}, srcPaths interface{}, dstDriveID interface{}, dstPath interface{}) *FSClientMock_Mv_Call {
	return &FSClientMock_Mv_Call{Call: _e.mock.On("Mv", ctx, userID, srcDriveID, srcPaths, dstDriveID, dstPath)}
}

func (_c *FSClientMock_Mv_Call) Run(run func(ctx context.Context, userID string, srcDriveID string, srcPaths []string, dstDriveID string, dstPath string)) *FSClientMock_Mv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *FSClientMock_Mv_Call) Return(err error) *FSClientMock_Mv_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FSClientMock_Mv_Call) RunAndReturn(run func(ctx context.Context, userID string, srcDriveID string, srcPaths []string, dstDriveID string, dstPath string) error) *FSClientMock_Mv_Call {
	_c.Call.Return(run)
	return _c
}

// PresignDownload provides a mock function for the type FSClientMock
func (_mock *FSClientMock) PresignDownload(ctx context.Context, userID string, driveID string, path string, expiry time.Duration) (vfs.PresignInfo, error) {
	ret := _mock.Called(ctx, userID, driveID, path, expiry)

	if len(ret) == 0 {
		panic("no return value specified for PresignDownload")
	}

	var r0 vfs.PresignInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, time.Duration) (vfs.PresignInfo, error)); ok {
		return returnFunc(ctx, userID, driveID, path, expiry)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, time.Duration) vfs.PresignInfo); ok {
		r0 = returnFunc(ctx, userID, driveID, path, expiry)
	} else {
		r0 = ret.Get(0).(vfs.PresignInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, userID, driveID, path, expiry)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FSClientMock_PresignDownload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignDownload'
type FSClientMock_PresignDownload_Call struct {
	*mock.Call
}

// PresignDownload is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - driveID string
//   - path string
//   - expiry time.Duration
func (_e *FSClientMock_Expecter) PresignDownload(ctx interface{}, userID interface{}, driveID interface{}, path interface{}, expiry interface{}) *FSClientMock_PresignDownload_Call {
	return &FSClientMock_PresignDownload_Call{Call: _e.mock.On("PresignDownload", ctx, userID, driveID, path, expiry)}
}

func (_c *FSClientMock_PresignDownload_Call) Run(run func(ctx context.Context, userID string, driveID string, path string, expiry time.Duration)) *FSClientMock_PresignDownload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Duration
		if args[4] != nil {
			arg4 = args[4].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *FSClientMock_PresignDownload_Call) Return(presignInfo vfs.PresignInfo, err error) *FSClientMock_PresignDownload_Call {
	_c.Call.Return(presignInfo, err)
	return _c
}

func (_c *FSClientMock_PresignDownload_Call) RunAndReturn(run func(ctx context.Context, userID string, driveID string, path string, expiry time.Duration) (vfs.PresignInfo, error)) *FSClientMock_PresignDownload_Call {
	_c.Call.Return(run)
	return _c
}

// Rm provides a mock function for the type FSClientMock
func (_mock *FSClientMock) Rm(ctx context.Context, userID string, driveID string, paths []string, recursive bool) error {
	ret := _mock.Called(ctx, userID, driveID, paths, recursive)

	if len(ret) == 0 {
		panic("no return value specified for Rm")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string, bool) error); ok {
		r0 = returnFunc(ctx, userID, driveID, paths, recursive)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FSClientMock_Rm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rm'
type FSClientMock_Rm_Call struct {
	*mock.Call
}

// Rm is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - driveID string
//   - paths []string
//   - recursive bool
func (_e *FSClientMock_Expecter) Rm(ctx interface{}, userID interface{}, driveID interface{}, paths interface{}, recursive interface{}) *FSClientMock_Rm_Call {
	return &FSClientMock_Rm_Call{Call: _e.mock.On("Rm", ctx, userID, driveID, paths, recursive)}
}

func (_c *FSClientMock_Rm_Call) Run(run func(ctx context.Context, userID string, driveID string, paths []string, recursive bool)) *FSClientMock_Rm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *FSClientMock_Rm_Call) Return(err error) *FSClientMock_Rm_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FSClientMock_Rm_Call) RunAndReturn(run func(ctx context.Context, userID string, driveID string, paths []string, recursive bool) error) *FSClientMock_Rm_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type FSClientMock
func (_mock *FSClientMock) Stat(ctx context.Context, userID string, driveID string, path string) (*node.Node, error) {
	ret := _mock.Called(ctx, userID, driveID, path)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 *node.Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*node.Node, error)); ok {
		return returnFunc(ctx, userID, driveID, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *node.Node); ok {
		r0 = returnFunc(ctx, userID, driveID, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*node.Node)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, driveID, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FSClientMock_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type FSClientMock_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - driveID string
//   - path string
func (_e *FSClientMock_Expecter) Stat(ctx interface{}, userID interface{}, driveID interface{}, path interface{}) *FSClientMock_Stat_Call {
	return &FSClientMock_Stat_Call{Call: _e.mock.On("Stat", ctx, userID, driveID, path)}
}

func (_c *FSClientMock_Stat_Call) Run(run func(ctx context.Context, userID string, driveID string, path string)) *FSClientMock_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *FSClientMock_Stat_Call) Return(node1 *node.Node, err error) *FSClientMock_Stat_Call {
	_c.Call.Return(node1, err)
	return _c
}

func (_c *FSClientMock_Stat_Call) RunAndReturn(run func(ctx context.Context, userID string, driveID string, path string) (*node.Node, error)) *FSClientMock_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// Symlink provides a mock function for the type FSClientMock
func (_mock *FSClientMock) Symlink(ctx context.Context, userID string, driveID string, target string, linkPath string) (*node.Node, error) {
	ret := _mock.Called(ctx, userID, driveID, target, linkPath)

	if len(ret) == 0 {
		panic("no return value specified for Symlink")
	}

	var r0 *node.Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*node.Node, error)); ok {
		return returnFunc(ctx, userID, driveID, target, linkPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *node.Node); ok {
		r0 = returnFunc(ctx, userID, driveID, target, linkPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*node.Node)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, driveID, target, linkPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FSClientMock_Symlink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Symlink'
type FSClientMock_Symlink_Call struct {
	*mock.Call
}

// Symlink is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - driveID string
//   - target string
//   - linkPath string
func (_e *FSClientMock_Expecter) Symlink(ctx interface{}, userID interface{}, driveID interface{}, target interface{}, linkPath interface{}) *FSClientMock_Symlink_Call {
	return &FSClientMock_Symlink_Call{Call: _e.mock.On("Symlink", ctx, userID, driveID, target, linkPath)}
}

func (_c *FSClientMock_Symlink_Call) Run(run func(ctx context.Context, userID string, driveID string, target string, linkPath string)) *FSClientMock_Symlink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *FSClientMock_Symlink_Call) Return(node1 *node.Node, err error) *FSClientMock_Symlink_Call {
	_c.Call.Return(node1, err)
	return _c
}

func (_c *FSClientMock_Symlink_Call) RunAndReturn(run func(ctx context.Context, userID string, driveID string, target string, linkPath string) (*node.Node, error)) *FSClientMock_Symlink_Call {
	_c.Call.Return(run)
	return _c
}

// Touch provides a mock function for the type FSClientMock
func (_mock *FSClientMock) Touch(ctx context.Context, userID string, driveID string, path string) (*node.Node, error) {
	ret := _mock.Called(ctx, userID, driveID, path)

	if len(ret) == 0 {
		panic("no return value specified for Touch")
	}

	var r0 *node.Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*node.Node, error)); ok {
		return returnFunc(ctx, userID, driveID, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *node.Node); ok {
		r0 = returnFunc(ctx, userID, driveID, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*node.Node)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, driveID, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FSClientMock_Touch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Touch'
type FSClientMock_Touch_Call struct {
	*mock.Call
}

// Touch is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - driveID string
//   - path string
func (_e *FSClientMock_Expecter) Touch(ctx interface{}, userID interface{}, driveID interface{}, path interface{}) *FSClientMock_Touch_Call {
	return &FSClientMock_Touch_Call{Call: _e.mock.On("Touch", ctx, userID, driveID, path)}
}

func (_c *FSClientMock_Touch_Call) Run(run func(ctx context.Context, userID string, driveID string, path string)) *FSClientMock_Touch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *FSClientMock_Touch_Call) Return(node1 *node.Node, err error) *FSClientMock_Touch_Call {
	_c.Call.Return(node1, err)
	return _c
}

func (_c *FSClientMock_Touch_Call) RunAndReturn(run func(ctx context.Context, userID string, driveID string, path string) (*node.Node, error)) *FSClientMock_Touch_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDrive provides a mock function for the type FSClientMock
func (_mock *FSClientMock) UpdateDrive(ctx context.Context, actorID string, id string, name *string, description *string) (*drive.Drive, error) {
	ret := _mock.Called(ctx, actorID, id, name, description)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDrive")
	}

	var r0 *drive.Drive
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string, *string) (*drive.Drive, error)); ok {
		return returnFunc(ctx, actorID, id, name, description)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string, *string) *drive.Drive); ok {
		r0 = returnFunc(ctx, actorID, id, name, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*drive.Drive)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *string, *string) error); ok {
		r1 = returnFunc(ctx, actorID, id, name, description)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FSClientMock_UpdateDrive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDrive'
type FSClientMock_UpdateDrive_Call struct {
	*mock.Call
}

// UpdateDrive is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - id string
//   - name *string
//   - description *string
func (_e *FSClientMock_Expecter) UpdateDrive(ctx interface{}, actorID interface{}, id interface{}, name interface{}, description interface{}) *FSClientMock_UpdateDrive_Call {
	return &FSClientMock_UpdateDrive_Call{Call: _e.mock.On("UpdateDrive", ctx, actorID, id, name, description)}
}

func (_c *FSClientMock_UpdateDrive_Call) Run(run func(ctx context.Context, actorID string, id string, name *string, description *string)) *FSClientMock_UpdateDrive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *FSClientMock_UpdateDrive_Call) Return(drive1 *drive.Drive, err error) *FSClientMock_UpdateDrive_Call {
	_c.Call.Return(drive1, err)
	return _c
}

func (_c *FSClientMock_UpdateDrive_Call) RunAndReturn(run func(ctx context.Context, actorID string, id string, name *string, description *string) (*drive.Drive, error)) *FSClientMock_UpdateDrive_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUser provides a mock function for the type FSClientMock
func (_mock *FSClientMock) UpsertUser(ctx context.Context, actorID string, cmd *user.CreateCommand) (*user.User, error) {
	ret := _mock.Called(ctx, actorID, cmd)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUser")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *user.CreateCommand) (*user.User, error)); ok {
		return returnFunc(ctx, actorID, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *user.CreateCommand) *user.User); ok {
		r0 = returnFunc(ctx, actorID, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *user.CreateCommand) error); ok {
		r1 = returnFunc(ctx, actorID, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FSClientMock_UpsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUser'
type FSClientMock_UpsertUser_Call struct {
	*mock.Call
}

// UpsertUser is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID string
//   - cmd *user.CreateCommand
func (_e *FSClientMock_Expecter) UpsertUser(ctx interface{}, actorID interface{}, cmd interface{}) *FSClientMock_UpsertUser_Call {
	return &FSClientMock_UpsertUser_Call{Call: _e.mock.On("UpsertUser", ctx, actorID, cmd)}
}

func (_c *FSClientMock_UpsertUser_Call) Run(run func(ctx context.Context, actorID string, cmd *user.CreateCommand)) *FSClientMock_UpsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *user.CreateCommand
		if args[2] != nil {
			arg2 = args[2].(*user.CreateCommand)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FSClientMock_UpsertUser_Call) Return(user1 *user.User, err error) *FSClientMock_UpsertUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *FSClientMock_UpsertUser_Call) RunAndReturn(run func(ctx context.Context, actorID string, cmd *user.CreateCommand) (*user.User, error)) *FSClientMock_UpsertUser_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type FSClientMock
func (_mock *FSClientMock) Write(ctx context.Context, userID string, driveID string, path string, content string) error {
	ret := _mock.Called(ctx, userID, driveID, path, content)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, userID, driveID, path, content)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FSClientMock_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type FSClientMock_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - driveID string
//   - path string
//   - content string
func (_e *FSClientMock_Expecter) Write(ctx interface{}, userID interface{}, driveID interface{}, path interface{}, content interface{}) *FSClientMock_Write_Call {
	return &FSClientMock_Write_Call{Call: _e.mock.On("Write", ctx, userID, driveID, path, content)}
}

func (_c *FSClientMock_Write_Call) Run(run func(ctx context.Context, userID string, driveID string, path string, content string)) *FSClientMock_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *FSClientMock_Write_Call) Return(err error) *FSClientMock_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FSClientMock_Write_Call) RunAndReturn(run func(ctx context.Context, userID string, driveID string, path string, content string) error) *FSClientMock_Write_Call {
	_c.Call.Return(run)
	return _c
}

// WriteLarge provides a mock function for the type FSClientMock
func (_mock *FSClientMock) WriteLarge(ctx context.Context, userID string, driveID string, path string, obj node.ObjectContent, size int64) error {
	ret := _mock.Called(ctx, userID, driveID, path, obj, size)

	if len(ret) == 0 {
		panic("no return value specified for WriteLarge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, node.ObjectContent, int64) error); ok {
		r0 = returnFunc(ctx, userID, driveID, path, obj, size)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FSClientMock_WriteLarge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteLarge'
type FSClientMock_WriteLarge_Call struct {
	*mock.Call
}

// WriteLarge is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - driveID string
//   - path string
//   - obj node.ObjectContent
//   - size int64
func (_e *FSClientMock_Expecter) WriteLarge(ctx interface{}, userID interface{}, driveID interface{}, path interface{}, obj interface{}, size interface{}) *FSClientMock_WriteLarge_Call {
	return &FSClientMock_WriteLarge_Call{Call: _e.mock.On("WriteLarge", ctx, userID, driveID, path, obj, size)}
}

func (_c *FSClientMock_WriteLarge_Call) Run(run func(ctx context.Context, userID string, driveID string, path string, obj node.ObjectContent, size int64)) *FSClientMock_WriteLarge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 node.ObjectContent
		if args[4] != nil {
			arg4 = args[4].(node.ObjectContent)
		}
		var arg5 int64
		if args[5] != nil {
			arg5 = args[5].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *FSClientMock_WriteLarge_Call) Return(err error) *FSClientMock_WriteLarge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FSClientMock_WriteLarge_Call) RunAndReturn(run func(ctx context.Context, userID string, driveID string, path string, obj node.ObjectContent, size int64) error) *FSClientMock_WriteLarge_Call {
	_c.Call.Return(run)
	return _c
}
