// Code generated by ent, DO NOT EDIT.

package node

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the node type in the database.
	Label = "node"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDriveID holds the string denoting the drive_id field in the database.
	FieldDriveID = "drive_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldNlink holds the string denoting the nlink field in the database.
	FieldNlink = "nlink"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldAtime holds the string denoting the atime field in the database.
	FieldAtime = "atime"
	// FieldMtime holds the string denoting the mtime field in the database.
	FieldMtime = "mtime"
	// FieldCtime holds the string denoting the ctime field in the database.
	FieldCtime = "ctime"
	// FieldCrtime holds the string denoting the crtime field in the database.
	FieldCrtime = "crtime"
	// FieldFlags holds the string denoting the flags field in the database.
	FieldFlags = "flags"
	// FieldRevision holds the string denoting the revision field in the database.
	FieldRevision = "revision"
	// Table holds the table name of the node in the database.
	Table = "nodes"
)

// Columns holds all SQL columns for node fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDriveID,
	FieldType,
	FieldSize,
	FieldNlink,
	FieldContent,
	FieldAtime,
	FieldMtime,
	FieldCtime,
	FieldCrtime,
	FieldFlags,
	FieldRevision,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DriveIDValidator is a validator for the "drive_id" field. It is called by the builders before save.
	DriveIDValidator func(string) error
	// DefaultSize holds the default value on creation for the "size" field.
	DefaultSize int64
	// DefaultNlink holds the default value on creation for the "nlink" field.
	DefaultNlink uint32
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func([]byte) error
	// DefaultFlags holds the default value on creation for the "flags" field.
	DefaultFlags uint32
	// RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	RevisionValidator func(string) error
)

// Type defines the type for the "type" enum field.
type Type string

// TypeFile is the default value of the Type enum.
const DefaultType = TypeFile

// Type values.
const (
	TypeFile      Type = "file"
	TypeDirectory Type = "directory"
	TypeSymlink   Type = "symlink"
	TypeObject    Type = "object"
	TypeDevice    Type = "device"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeFile, TypeDirectory, TypeSymlink, TypeObject, TypeDevice:
		return nil
	default:
		return fmt.Errorf("node: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the Node queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDriveID orders the results by the drive_id field.
func ByDriveID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDriveID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// ByNlink orders the results by the nlink field.
func ByNlink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNlink, opts...).ToFunc()
}

// ByAtime orders the results by the atime field.
func ByAtime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAtime, opts...).ToFunc()
}

// ByMtime orders the results by the mtime field.
func ByMtime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMtime, opts...).ToFunc()
}

// ByCtime orders the results by the ctime field.
func ByCtime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCtime, opts...).ToFunc()
}

// ByCrtime orders the results by the crtime field.
func ByCrtime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCrtime, opts...).ToFunc()
}

// ByFlags orders the results by the flags field.
func ByFlags(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFlags, opts...).ToFunc()
}

// ByRevision orders the results by the revision field.
func ByRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevision, opts...).ToFunc()
}
