// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gcMocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewRunnerMock creates a new instance of RunnerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRunnerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RunnerMock {
	mock := &RunnerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RunnerMock is an autogenerated mock type for the Runner type
type RunnerMock struct {
	mock.Mock
}

type RunnerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RunnerMock) EXPECT() *RunnerMock_Expecter {
	return &RunnerMock_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type RunnerMock
func (_mock *RunnerMock) Run(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RunnerMock_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type RunnerMock_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RunnerMock_Expecter) Run(ctx interface{}) *RunnerMock_Run_Call {
	return &RunnerMock_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *RunnerMock_Run_Call) Run(run func(ctx context.Context)) *RunnerMock_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RunnerMock_Run_Call) Return(err error) *RunnerMock_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RunnerMock_Run_Call) RunAndReturn(run func(ctx context.Context) error) *RunnerMock_Run_Call {
	_c.Call.Return(run)
	return _c
}
