// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mandacode-labs/mdrive/ent/drive"
	"github.com/mandacode-labs/mdrive/ent/predicate"
	"github.com/mandacode-labs/mdrive/ent/storage"
	"github.com/mandacode-labs/mdrive/ent/superblock"
	"github.com/mandacode-labs/mdrive/ent/user"
)

// DriveUpdate is the builder for updating Drive entities.
type DriveUpdate struct {
	config
	hooks    []Hook
	mutation *DriveMutation
}

// Where appends a list predicates to the DriveUpdate builder.
func (_u *DriveUpdate) Where(ps ...predicate.Drive) *DriveUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *DriveUpdate) SetUpdateTime(v time.Time) *DriveUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetName sets the "name" field.
func (_u *DriveUpdate) SetName(v string) *DriveUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DriveUpdate) SetNillableName(v *string) *DriveUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DriveUpdate) SetDescription(v string) *DriveUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DriveUpdate) SetNillableDescription(v *string) *DriveUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DriveUpdate) ClearDescription() *DriveUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *DriveUpdate) SetOwnerID(v string) *DriveUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *DriveUpdate) SetNillableOwnerID(v *string) *DriveUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DriveUpdate) SetDeletedAt(v time.Time) *DriveUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DriveUpdate) SetNillableDeletedAt(v *time.Time) *DriveUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DriveUpdate) ClearDeletedAt() *DriveUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetStorageID sets the "storage" edge to the Storage entity by ID.
func (_u *DriveUpdate) SetStorageID(id int) *DriveUpdate {
	_u.mutation.SetStorageID(id)
	return _u
}

// SetNillableStorageID sets the "storage" edge to the Storage entity by ID if the given value is not nil.
func (_u *DriveUpdate) SetNillableStorageID(id *int) *DriveUpdate {
	if id != nil {
		_u = _u.SetStorageID(*id)
	}
	return _u
}

// SetStorage sets the "storage" edge to the Storage entity.
func (_u *DriveUpdate) SetStorage(v *Storage) *DriveUpdate {
	return _u.SetStorageID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *DriveUpdate) SetUserID(id string) *DriveUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DriveUpdate) SetUser(v *User) *DriveUpdate {
	return _u.SetUserID(v.ID)
}

// SetSuperblockID sets the "superblock" edge to the Superblock entity by ID.
func (_u *DriveUpdate) SetSuperblockID(id uuid.UUID) *DriveUpdate {
	_u.mutation.SetSuperblockID(id)
	return _u
}

// SetNillableSuperblockID sets the "superblock" edge to the Superblock entity by ID if the given value is not nil.
func (_u *DriveUpdate) SetNillableSuperblockID(id *uuid.UUID) *DriveUpdate {
	if id != nil {
		_u = _u.SetSuperblockID(*id)
	}
	return _u
}

// SetSuperblock sets the "superblock" edge to the Superblock entity.
func (_u *DriveUpdate) SetSuperblock(v *Superblock) *DriveUpdate {
	return _u.SetSuperblockID(v.ID)
}

// Mutation returns the DriveMutation object of the builder.
func (_u *DriveUpdate) Mutation() *DriveMutation {
	return _u.mutation
}

// ClearStorage clears the "storage" edge to the Storage entity.
func (_u *DriveUpdate) ClearStorage() *DriveUpdate {
	_u.mutation.ClearStorage()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DriveUpdate) ClearUser() *DriveUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearSuperblock clears the "superblock" edge to the Superblock entity.
func (_u *DriveUpdate) ClearSuperblock() *DriveUpdate {
	_u.mutation.ClearSuperblock()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DriveUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DriveUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DriveUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DriveUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DriveUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := drive.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DriveUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := drive.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Drive.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := drive.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Drive.description": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Drive.user"`)
	}
	return nil
}

func (_u *DriveUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(drive.Table, drive.Columns, sqlgraph.NewFieldSpec(drive.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(drive.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(drive.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(drive.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(drive.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(drive.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(drive.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.StorageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   drive.StorageTable,
			Columns: []string{drive.StorageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StorageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   drive.StorageTable,
			Columns: []string{drive.StorageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drive.UserTable,
			Columns: []string{drive.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drive.UserTable,
			Columns: []string{drive.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SuperblockCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   drive.SuperblockTable,
			Columns: []string{drive.SuperblockColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(superblock.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SuperblockIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   drive.SuperblockTable,
			Columns: []string{drive.SuperblockColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(superblock.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{drive.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DriveUpdateOne is the builder for updating a single Drive entity.
type DriveUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DriveMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *DriveUpdateOne) SetUpdateTime(v time.Time) *DriveUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetName sets the "name" field.
func (_u *DriveUpdateOne) SetName(v string) *DriveUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DriveUpdateOne) SetNillableName(v *string) *DriveUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DriveUpdateOne) SetDescription(v string) *DriveUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DriveUpdateOne) SetNillableDescription(v *string) *DriveUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DriveUpdateOne) ClearDescription() *DriveUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *DriveUpdateOne) SetOwnerID(v string) *DriveUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *DriveUpdateOne) SetNillableOwnerID(v *string) *DriveUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DriveUpdateOne) SetDeletedAt(v time.Time) *DriveUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DriveUpdateOne) SetNillableDeletedAt(v *time.Time) *DriveUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DriveUpdateOne) ClearDeletedAt() *DriveUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetStorageID sets the "storage" edge to the Storage entity by ID.
func (_u *DriveUpdateOne) SetStorageID(id int) *DriveUpdateOne {
	_u.mutation.SetStorageID(id)
	return _u
}

// SetNillableStorageID sets the "storage" edge to the Storage entity by ID if the given value is not nil.
func (_u *DriveUpdateOne) SetNillableStorageID(id *int) *DriveUpdateOne {
	if id != nil {
		_u = _u.SetStorageID(*id)
	}
	return _u
}

// SetStorage sets the "storage" edge to the Storage entity.
func (_u *DriveUpdateOne) SetStorage(v *Storage) *DriveUpdateOne {
	return _u.SetStorageID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *DriveUpdateOne) SetUserID(id string) *DriveUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DriveUpdateOne) SetUser(v *User) *DriveUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetSuperblockID sets the "superblock" edge to the Superblock entity by ID.
func (_u *DriveUpdateOne) SetSuperblockID(id uuid.UUID) *DriveUpdateOne {
	_u.mutation.SetSuperblockID(id)
	return _u
}

// SetNillableSuperblockID sets the "superblock" edge to the Superblock entity by ID if the given value is not nil.
func (_u *DriveUpdateOne) SetNillableSuperblockID(id *uuid.UUID) *DriveUpdateOne {
	if id != nil {
		_u = _u.SetSuperblockID(*id)
	}
	return _u
}

// SetSuperblock sets the "superblock" edge to the Superblock entity.
func (_u *DriveUpdateOne) SetSuperblock(v *Superblock) *DriveUpdateOne {
	return _u.SetSuperblockID(v.ID)
}

// Mutation returns the DriveMutation object of the builder.
func (_u *DriveUpdateOne) Mutation() *DriveMutation {
	return _u.mutation
}

// ClearStorage clears the "storage" edge to the Storage entity.
func (_u *DriveUpdateOne) ClearStorage() *DriveUpdateOne {
	_u.mutation.ClearStorage()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DriveUpdateOne) ClearUser() *DriveUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearSuperblock clears the "superblock" edge to the Superblock entity.
func (_u *DriveUpdateOne) ClearSuperblock() *DriveUpdateOne {
	_u.mutation.ClearSuperblock()
	return _u
}

// Where appends a list predicates to the DriveUpdate builder.
func (_u *DriveUpdateOne) Where(ps ...predicate.Drive) *DriveUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DriveUpdateOne) Select(field string, fields ...string) *DriveUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Drive entity.
func (_u *DriveUpdateOne) Save(ctx context.Context) (*Drive, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DriveUpdateOne) SaveX(ctx context.Context) *Drive {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DriveUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DriveUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DriveUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := drive.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DriveUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := drive.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Drive.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := drive.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Drive.description": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Drive.user"`)
	}
	return nil
}

func (_u *DriveUpdateOne) sqlSave(ctx context.Context) (_node *Drive, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(drive.Table, drive.Columns, sqlgraph.NewFieldSpec(drive.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Drive.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, drive.FieldID)
		for _, f := range fields {
			if !drive.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != drive.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(drive.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(drive.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(drive.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(drive.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(drive.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(drive.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.StorageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   drive.StorageTable,
			Columns: []string{drive.StorageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StorageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   drive.StorageTable,
			Columns: []string{drive.StorageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drive.UserTable,
			Columns: []string{drive.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   drive.UserTable,
			Columns: []string{drive.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SuperblockCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   drive.SuperblockTable,
			Columns: []string{drive.SuperblockColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(superblock.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SuperblockIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   drive.SuperblockTable,
			Columns: []string{drive.SuperblockColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(superblock.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Drive{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{drive.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
