// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mandacode-labs/mdrive/ent/node"
)

// NodeCreate is the builder for creating a Node entity.
type NodeCreate struct {
	config
	mutation *NodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *NodeCreate) SetCreateTime(v time.Time) *NodeCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *NodeCreate) SetNillableCreateTime(v *time.Time) *NodeCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *NodeCreate) SetUpdateTime(v time.Time) *NodeCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *NodeCreate) SetNillableUpdateTime(v *time.Time) *NodeCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *NodeCreate) SetKind(v node.Kind) *NodeCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *NodeCreate) SetNillableKind(v *node.Kind) *NodeCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetSize sets the "size" field.
func (_c *NodeCreate) SetSize(v int64) *NodeCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *NodeCreate) SetNillableSize(v *int64) *NodeCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetNlink sets the "nlink" field.
func (_c *NodeCreate) SetNlink(v uint32) *NodeCreate {
	_c.mutation.SetNlink(v)
	return _c
}

// SetNillableNlink sets the "nlink" field if the given value is not nil.
func (_c *NodeCreate) SetNillableNlink(v *uint32) *NodeCreate {
	if v != nil {
		_c.SetNlink(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *NodeCreate) SetContent(v []byte) *NodeCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetAtime sets the "atime" field.
func (_c *NodeCreate) SetAtime(v time.Time) *NodeCreate {
	_c.mutation.SetAtime(v)
	return _c
}

// SetMtime sets the "mtime" field.
func (_c *NodeCreate) SetMtime(v time.Time) *NodeCreate {
	_c.mutation.SetMtime(v)
	return _c
}

// SetCtime sets the "ctime" field.
func (_c *NodeCreate) SetCtime(v time.Time) *NodeCreate {
	_c.mutation.SetCtime(v)
	return _c
}

// SetCrtime sets the "crtime" field.
func (_c *NodeCreate) SetCrtime(v time.Time) *NodeCreate {
	_c.mutation.SetCrtime(v)
	return _c
}

// SetFlags sets the "flags" field.
func (_c *NodeCreate) SetFlags(v uint32) *NodeCreate {
	_c.mutation.SetFlags(v)
	return _c
}

// SetNillableFlags sets the "flags" field if the given value is not nil.
func (_c *NodeCreate) SetNillableFlags(v *uint32) *NodeCreate {
	if v != nil {
		_c.SetFlags(*v)
	}
	return _c
}

// SetRevision sets the "revision" field.
func (_c *NodeCreate) SetRevision(v string) *NodeCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetID sets the "id" field.
func (_c *NodeCreate) SetID(v uuid.UUID) *NodeCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the NodeMutation object of the builder.
func (_c *NodeCreate) Mutation() *NodeMutation {
	return _c.mutation
}

// Save creates the Node in the database.
func (_c *NodeCreate) Save(ctx context.Context) (*Node, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NodeCreate) SaveX(ctx context.Context) *Node {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NodeCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := node.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := node.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.Kind(); !ok {
		v := node.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.Size(); !ok {
		v := node.DefaultSize
		_c.mutation.SetSize(v)
	}
	if _, ok := _c.mutation.Nlink(); !ok {
		v := node.DefaultNlink
		_c.mutation.SetNlink(v)
	}
	if _, ok := _c.mutation.Flags(); !ok {
		v := node.DefaultFlags
		_c.mutation.SetFlags(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NodeCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Node.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Node.update_time"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Node.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := node.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Node.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "Node.size"`)}
	}
	if _, ok := _c.mutation.Nlink(); !ok {
		return &ValidationError{Name: "nlink", err: errors.New(`ent: missing required field "Node.nlink"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := node.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Node.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Atime(); !ok {
		return &ValidationError{Name: "atime", err: errors.New(`ent: missing required field "Node.atime"`)}
	}
	if _, ok := _c.mutation.Mtime(); !ok {
		return &ValidationError{Name: "mtime", err: errors.New(`ent: missing required field "Node.mtime"`)}
	}
	if _, ok := _c.mutation.Ctime(); !ok {
		return &ValidationError{Name: "ctime", err: errors.New(`ent: missing required field "Node.ctime"`)}
	}
	if _, ok := _c.mutation.Crtime(); !ok {
		return &ValidationError{Name: "crtime", err: errors.New(`ent: missing required field "Node.crtime"`)}
	}
	if _, ok := _c.mutation.Flags(); !ok {
		return &ValidationError{Name: "flags", err: errors.New(`ent: missing required field "Node.flags"`)}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "Node.revision"`)}
	}
	if v, ok := _c.mutation.Revision(); ok {
		if err := node.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "Node.revision": %w`, err)}
		}
	}
	return nil
}

func (_c *NodeCreate) sqlSave(ctx context.Context) (*Node, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NodeCreate) createSpec() (*Node, *sqlgraph.CreateSpec) {
	var (
		_node = &Node{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(node.Table, sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(node.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(node.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(node.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(node.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Nlink(); ok {
		_spec.SetField(node.FieldNlink, field.TypeUint32, value)
		_node.Nlink = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(node.FieldContent, field.TypeBytes, value)
		_node.Content = &value
	}
	if value, ok := _c.mutation.Atime(); ok {
		_spec.SetField(node.FieldAtime, field.TypeTime, value)
		_node.Atime = value
	}
	if value, ok := _c.mutation.Mtime(); ok {
		_spec.SetField(node.FieldMtime, field.TypeTime, value)
		_node.Mtime = value
	}
	if value, ok := _c.mutation.Ctime(); ok {
		_spec.SetField(node.FieldCtime, field.TypeTime, value)
		_node.Ctime = value
	}
	if value, ok := _c.mutation.Crtime(); ok {
		_spec.SetField(node.FieldCrtime, field.TypeTime, value)
		_node.Crtime = value
	}
	if value, ok := _c.mutation.Flags(); ok {
		_spec.SetField(node.FieldFlags, field.TypeUint32, value)
		_node.Flags = value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(node.FieldRevision, field.TypeString, value)
		_node.Revision = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Node.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NodeUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *NodeCreate) OnConflict(opts ...sql.ConflictOption) *NodeUpsertOne {
	_c.conflict = opts
	return &NodeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Node.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NodeCreate) OnConflictColumns(columns ...string) *NodeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NodeUpsertOne{
		create: _c,
	}
}

type (
	// NodeUpsertOne is the builder for "upsert"-ing
	//  one Node node.
	NodeUpsertOne struct {
		create *NodeCreate
	}

	// NodeUpsert is the "OnConflict" setter.
	NodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *NodeUpsert) SetUpdateTime(v time.Time) *NodeUpsert {
	u.Set(node.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *NodeUpsert) UpdateUpdateTime() *NodeUpsert {
	u.SetExcluded(node.FieldUpdateTime)
	return u
}

// SetKind sets the "kind" field.
func (u *NodeUpsert) SetKind(v node.Kind) *NodeUpsert {
	u.Set(node.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *NodeUpsert) UpdateKind() *NodeUpsert {
	u.SetExcluded(node.FieldKind)
	return u
}

// SetSize sets the "size" field.
func (u *NodeUpsert) SetSize(v int64) *NodeUpsert {
	u.Set(node.FieldSize, v)
	return u
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *NodeUpsert) UpdateSize() *NodeUpsert {
	u.SetExcluded(node.FieldSize)
	return u
}

// AddSize adds v to the "size" field.
func (u *NodeUpsert) AddSize(v int64) *NodeUpsert {
	u.Add(node.FieldSize, v)
	return u
}

// SetNlink sets the "nlink" field.
func (u *NodeUpsert) SetNlink(v uint32) *NodeUpsert {
	u.Set(node.FieldNlink, v)
	return u
}

// UpdateNlink sets the "nlink" field to the value that was provided on create.
func (u *NodeUpsert) UpdateNlink() *NodeUpsert {
	u.SetExcluded(node.FieldNlink)
	return u
}

// AddNlink adds v to the "nlink" field.
func (u *NodeUpsert) AddNlink(v uint32) *NodeUpsert {
	u.Add(node.FieldNlink, v)
	return u
}

// SetContent sets the "content" field.
func (u *NodeUpsert) SetContent(v []byte) *NodeUpsert {
	u.Set(node.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *NodeUpsert) UpdateContent() *NodeUpsert {
	u.SetExcluded(node.FieldContent)
	return u
}

// ClearContent clears the value of the "content" field.
func (u *NodeUpsert) ClearContent() *NodeUpsert {
	u.SetNull(node.FieldContent)
	return u
}

// SetAtime sets the "atime" field.
func (u *NodeUpsert) SetAtime(v time.Time) *NodeUpsert {
	u.Set(node.FieldAtime, v)
	return u
}

// UpdateAtime sets the "atime" field to the value that was provided on create.
func (u *NodeUpsert) UpdateAtime() *NodeUpsert {
	u.SetExcluded(node.FieldAtime)
	return u
}

// SetMtime sets the "mtime" field.
func (u *NodeUpsert) SetMtime(v time.Time) *NodeUpsert {
	u.Set(node.FieldMtime, v)
	return u
}

// UpdateMtime sets the "mtime" field to the value that was provided on create.
func (u *NodeUpsert) UpdateMtime() *NodeUpsert {
	u.SetExcluded(node.FieldMtime)
	return u
}

// SetCtime sets the "ctime" field.
func (u *NodeUpsert) SetCtime(v time.Time) *NodeUpsert {
	u.Set(node.FieldCtime, v)
	return u
}

// UpdateCtime sets the "ctime" field to the value that was provided on create.
func (u *NodeUpsert) UpdateCtime() *NodeUpsert {
	u.SetExcluded(node.FieldCtime)
	return u
}

// SetCrtime sets the "crtime" field.
func (u *NodeUpsert) SetCrtime(v time.Time) *NodeUpsert {
	u.Set(node.FieldCrtime, v)
	return u
}

// UpdateCrtime sets the "crtime" field to the value that was provided on create.
func (u *NodeUpsert) UpdateCrtime() *NodeUpsert {
	u.SetExcluded(node.FieldCrtime)
	return u
}

// SetFlags sets the "flags" field.
func (u *NodeUpsert) SetFlags(v uint32) *NodeUpsert {
	u.Set(node.FieldFlags, v)
	return u
}

// UpdateFlags sets the "flags" field to the value that was provided on create.
func (u *NodeUpsert) UpdateFlags() *NodeUpsert {
	u.SetExcluded(node.FieldFlags)
	return u
}

// AddFlags adds v to the "flags" field.
func (u *NodeUpsert) AddFlags(v uint32) *NodeUpsert {
	u.Add(node.FieldFlags, v)
	return u
}

// SetRevision sets the "revision" field.
func (u *NodeUpsert) SetRevision(v string) *NodeUpsert {
	u.Set(node.FieldRevision, v)
	return u
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *NodeUpsert) UpdateRevision() *NodeUpsert {
	u.SetExcluded(node.FieldRevision)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Node.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(node.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NodeUpsertOne) UpdateNewValues() *NodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(node.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(node.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Node.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NodeUpsertOne) Ignore() *NodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NodeUpsertOne) DoNothing() *NodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NodeCreate.OnConflict
// documentation for more info.
func (u *NodeUpsertOne) Update(set func(*NodeUpsert)) *NodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *NodeUpsertOne) SetUpdateTime(v time.Time) *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *NodeUpsertOne) UpdateUpdateTime() *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetKind sets the "kind" field.
func (u *NodeUpsertOne) SetKind(v node.Kind) *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *NodeUpsertOne) UpdateKind() *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateKind()
	})
}

// SetSize sets the "size" field.
func (u *NodeUpsertOne) SetSize(v int64) *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *NodeUpsertOne) AddSize(v int64) *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *NodeUpsertOne) UpdateSize() *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateSize()
	})
}

// SetNlink sets the "nlink" field.
func (u *NodeUpsertOne) SetNlink(v uint32) *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.SetNlink(v)
	})
}

// AddNlink adds v to the "nlink" field.
func (u *NodeUpsertOne) AddNlink(v uint32) *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.AddNlink(v)
	})
}

// UpdateNlink sets the "nlink" field to the value that was provided on create.
func (u *NodeUpsertOne) UpdateNlink() *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateNlink()
	})
}

// SetContent sets the "content" field.
func (u *NodeUpsertOne) SetContent(v []byte) *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *NodeUpsertOne) UpdateContent() *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *NodeUpsertOne) ClearContent() *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.ClearContent()
	})
}

// SetAtime sets the "atime" field.
func (u *NodeUpsertOne) SetAtime(v time.Time) *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.SetAtime(v)
	})
}

// UpdateAtime sets the "atime" field to the value that was provided on create.
func (u *NodeUpsertOne) UpdateAtime() *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateAtime()
	})
}

// SetMtime sets the "mtime" field.
func (u *NodeUpsertOne) SetMtime(v time.Time) *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.SetMtime(v)
	})
}

// UpdateMtime sets the "mtime" field to the value that was provided on create.
func (u *NodeUpsertOne) UpdateMtime() *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateMtime()
	})
}

// SetCtime sets the "ctime" field.
func (u *NodeUpsertOne) SetCtime(v time.Time) *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.SetCtime(v)
	})
}

// UpdateCtime sets the "ctime" field to the value that was provided on create.
func (u *NodeUpsertOne) UpdateCtime() *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateCtime()
	})
}

// SetCrtime sets the "crtime" field.
func (u *NodeUpsertOne) SetCrtime(v time.Time) *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.SetCrtime(v)
	})
}

// UpdateCrtime sets the "crtime" field to the value that was provided on create.
func (u *NodeUpsertOne) UpdateCrtime() *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateCrtime()
	})
}

// SetFlags sets the "flags" field.
func (u *NodeUpsertOne) SetFlags(v uint32) *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.SetFlags(v)
	})
}

// AddFlags adds v to the "flags" field.
func (u *NodeUpsertOne) AddFlags(v uint32) *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.AddFlags(v)
	})
}

// UpdateFlags sets the "flags" field to the value that was provided on create.
func (u *NodeUpsertOne) UpdateFlags() *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateFlags()
	})
}

// SetRevision sets the "revision" field.
func (u *NodeUpsertOne) SetRevision(v string) *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.SetRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *NodeUpsertOne) UpdateRevision() *NodeUpsertOne {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateRevision()
	})
}

// Exec executes the query.
func (u *NodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NodeUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: NodeUpsertOne.ID is not supported by MySQL driver. Use NodeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NodeUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NodeCreateBulk is the builder for creating many Node entities in bulk.
type NodeCreateBulk struct {
	config
	err      error
	builders []*NodeCreate
	conflict []sql.ConflictOption
}

// Save creates the Node entities in the database.
func (_c *NodeCreateBulk) Save(ctx context.Context) ([]*Node, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Node, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NodeCreateBulk) SaveX(ctx context.Context) []*Node {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Node.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NodeUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *NodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *NodeUpsertBulk {
	_c.conflict = opts
	return &NodeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Node.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NodeCreateBulk) OnConflictColumns(columns ...string) *NodeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NodeUpsertBulk{
		create: _c,
	}
}

// NodeUpsertBulk is the builder for "upsert"-ing
// a bulk of Node nodes.
type NodeUpsertBulk struct {
	create *NodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Node.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(node.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NodeUpsertBulk) UpdateNewValues() *NodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(node.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(node.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Node.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NodeUpsertBulk) Ignore() *NodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NodeUpsertBulk) DoNothing() *NodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NodeCreateBulk.OnConflict
// documentation for more info.
func (u *NodeUpsertBulk) Update(set func(*NodeUpsert)) *NodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *NodeUpsertBulk) SetUpdateTime(v time.Time) *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *NodeUpsertBulk) UpdateUpdateTime() *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetKind sets the "kind" field.
func (u *NodeUpsertBulk) SetKind(v node.Kind) *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *NodeUpsertBulk) UpdateKind() *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateKind()
	})
}

// SetSize sets the "size" field.
func (u *NodeUpsertBulk) SetSize(v int64) *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *NodeUpsertBulk) AddSize(v int64) *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *NodeUpsertBulk) UpdateSize() *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateSize()
	})
}

// SetNlink sets the "nlink" field.
func (u *NodeUpsertBulk) SetNlink(v uint32) *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.SetNlink(v)
	})
}

// AddNlink adds v to the "nlink" field.
func (u *NodeUpsertBulk) AddNlink(v uint32) *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.AddNlink(v)
	})
}

// UpdateNlink sets the "nlink" field to the value that was provided on create.
func (u *NodeUpsertBulk) UpdateNlink() *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateNlink()
	})
}

// SetContent sets the "content" field.
func (u *NodeUpsertBulk) SetContent(v []byte) *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *NodeUpsertBulk) UpdateContent() *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *NodeUpsertBulk) ClearContent() *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.ClearContent()
	})
}

// SetAtime sets the "atime" field.
func (u *NodeUpsertBulk) SetAtime(v time.Time) *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.SetAtime(v)
	})
}

// UpdateAtime sets the "atime" field to the value that was provided on create.
func (u *NodeUpsertBulk) UpdateAtime() *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateAtime()
	})
}

// SetMtime sets the "mtime" field.
func (u *NodeUpsertBulk) SetMtime(v time.Time) *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.SetMtime(v)
	})
}

// UpdateMtime sets the "mtime" field to the value that was provided on create.
func (u *NodeUpsertBulk) UpdateMtime() *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateMtime()
	})
}

// SetCtime sets the "ctime" field.
func (u *NodeUpsertBulk) SetCtime(v time.Time) *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.SetCtime(v)
	})
}

// UpdateCtime sets the "ctime" field to the value that was provided on create.
func (u *NodeUpsertBulk) UpdateCtime() *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateCtime()
	})
}

// SetCrtime sets the "crtime" field.
func (u *NodeUpsertBulk) SetCrtime(v time.Time) *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.SetCrtime(v)
	})
}

// UpdateCrtime sets the "crtime" field to the value that was provided on create.
func (u *NodeUpsertBulk) UpdateCrtime() *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateCrtime()
	})
}

// SetFlags sets the "flags" field.
func (u *NodeUpsertBulk) SetFlags(v uint32) *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.SetFlags(v)
	})
}

// AddFlags adds v to the "flags" field.
func (u *NodeUpsertBulk) AddFlags(v uint32) *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.AddFlags(v)
	})
}

// UpdateFlags sets the "flags" field to the value that was provided on create.
func (u *NodeUpsertBulk) UpdateFlags() *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateFlags()
	})
}

// SetRevision sets the "revision" field.
func (u *NodeUpsertBulk) SetRevision(v string) *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.SetRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *NodeUpsertBulk) UpdateRevision() *NodeUpsertBulk {
	return u.Update(func(s *NodeUpsert) {
		s.UpdateRevision()
	})
}

// Exec executes the query.
func (u *NodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
