// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mandacode-labs/mdrive/ent/node"
	"github.com/mandacode-labs/mdrive/ent/predicate"
)

// NodeUpdate is the builder for updating Node entities.
type NodeUpdate struct {
	config
	hooks    []Hook
	mutation *NodeMutation
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdate) Where(ps ...predicate.Node) *NodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *NodeUpdate) SetUpdateTime(v time.Time) *NodeUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetType sets the "type" field.
func (_u *NodeUpdate) SetType(v node.Type) *NodeUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableType(v *node.Type) *NodeUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NodeUpdate) SetStatus(v node.Status) *NodeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableStatus(v *node.Status) *NodeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *NodeUpdate) SetSize(v int64) *NodeUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableSize(v *int64) *NodeUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *NodeUpdate) AddSize(v int64) *NodeUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetNlink sets the "nlink" field.
func (_u *NodeUpdate) SetNlink(v uint32) *NodeUpdate {
	_u.mutation.ResetNlink()
	_u.mutation.SetNlink(v)
	return _u
}

// SetNillableNlink sets the "nlink" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableNlink(v *uint32) *NodeUpdate {
	if v != nil {
		_u.SetNlink(*v)
	}
	return _u
}

// AddNlink adds value to the "nlink" field.
func (_u *NodeUpdate) AddNlink(v int32) *NodeUpdate {
	_u.mutation.AddNlink(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *NodeUpdate) SetContent(v []byte) *NodeUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *NodeUpdate) ClearContent() *NodeUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetAtime sets the "atime" field.
func (_u *NodeUpdate) SetAtime(v time.Time) *NodeUpdate {
	_u.mutation.SetAtime(v)
	return _u
}

// SetNillableAtime sets the "atime" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableAtime(v *time.Time) *NodeUpdate {
	if v != nil {
		_u.SetAtime(*v)
	}
	return _u
}

// SetMtime sets the "mtime" field.
func (_u *NodeUpdate) SetMtime(v time.Time) *NodeUpdate {
	_u.mutation.SetMtime(v)
	return _u
}

// SetNillableMtime sets the "mtime" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableMtime(v *time.Time) *NodeUpdate {
	if v != nil {
		_u.SetMtime(*v)
	}
	return _u
}

// SetCtime sets the "ctime" field.
func (_u *NodeUpdate) SetCtime(v time.Time) *NodeUpdate {
	_u.mutation.SetCtime(v)
	return _u
}

// SetNillableCtime sets the "ctime" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableCtime(v *time.Time) *NodeUpdate {
	if v != nil {
		_u.SetCtime(*v)
	}
	return _u
}

// SetCrtime sets the "crtime" field.
func (_u *NodeUpdate) SetCrtime(v time.Time) *NodeUpdate {
	_u.mutation.SetCrtime(v)
	return _u
}

// SetNillableCrtime sets the "crtime" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableCrtime(v *time.Time) *NodeUpdate {
	if v != nil {
		_u.SetCrtime(*v)
	}
	return _u
}

// SetFlags sets the "flags" field.
func (_u *NodeUpdate) SetFlags(v uint32) *NodeUpdate {
	_u.mutation.ResetFlags()
	_u.mutation.SetFlags(v)
	return _u
}

// SetNillableFlags sets the "flags" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableFlags(v *uint32) *NodeUpdate {
	if v != nil {
		_u.SetFlags(*v)
	}
	return _u
}

// AddFlags adds value to the "flags" field.
func (_u *NodeUpdate) AddFlags(v int32) *NodeUpdate {
	_u.mutation.AddFlags(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *NodeUpdate) SetRevision(v string) *NodeUpdate {
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableRevision(v *string) *NodeUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdate) Mutation() *NodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := node.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := node.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Node.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := node.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Node.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := node.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Node.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := node.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "Node.revision": %w`, err)}
		}
	}
	return nil
}

func (_u *NodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(node.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(node.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(node.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(node.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(node.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Nlink(); ok {
		_spec.SetField(node.FieldNlink, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedNlink(); ok {
		_spec.AddField(node.FieldNlink, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(node.FieldContent, field.TypeBytes, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(node.FieldContent, field.TypeBytes)
	}
	if value, ok := _u.mutation.Atime(); ok {
		_spec.SetField(node.FieldAtime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Mtime(); ok {
		_spec.SetField(node.FieldMtime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Ctime(); ok {
		_spec.SetField(node.FieldCtime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Crtime(); ok {
		_spec.SetField(node.FieldCrtime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Flags(); ok {
		_spec.SetField(node.FieldFlags, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedFlags(); ok {
		_spec.AddField(node.FieldFlags, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(node.FieldRevision, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NodeUpdateOne is the builder for updating a single Node entity.
type NodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *NodeUpdateOne) SetUpdateTime(v time.Time) *NodeUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetType sets the "type" field.
func (_u *NodeUpdateOne) SetType(v node.Type) *NodeUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableType(v *node.Type) *NodeUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NodeUpdateOne) SetStatus(v node.Status) *NodeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableStatus(v *node.Status) *NodeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *NodeUpdateOne) SetSize(v int64) *NodeUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableSize(v *int64) *NodeUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *NodeUpdateOne) AddSize(v int64) *NodeUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetNlink sets the "nlink" field.
func (_u *NodeUpdateOne) SetNlink(v uint32) *NodeUpdateOne {
	_u.mutation.ResetNlink()
	_u.mutation.SetNlink(v)
	return _u
}

// SetNillableNlink sets the "nlink" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableNlink(v *uint32) *NodeUpdateOne {
	if v != nil {
		_u.SetNlink(*v)
	}
	return _u
}

// AddNlink adds value to the "nlink" field.
func (_u *NodeUpdateOne) AddNlink(v int32) *NodeUpdateOne {
	_u.mutation.AddNlink(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *NodeUpdateOne) SetContent(v []byte) *NodeUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *NodeUpdateOne) ClearContent() *NodeUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetAtime sets the "atime" field.
func (_u *NodeUpdateOne) SetAtime(v time.Time) *NodeUpdateOne {
	_u.mutation.SetAtime(v)
	return _u
}

// SetNillableAtime sets the "atime" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableAtime(v *time.Time) *NodeUpdateOne {
	if v != nil {
		_u.SetAtime(*v)
	}
	return _u
}

// SetMtime sets the "mtime" field.
func (_u *NodeUpdateOne) SetMtime(v time.Time) *NodeUpdateOne {
	_u.mutation.SetMtime(v)
	return _u
}

// SetNillableMtime sets the "mtime" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableMtime(v *time.Time) *NodeUpdateOne {
	if v != nil {
		_u.SetMtime(*v)
	}
	return _u
}

// SetCtime sets the "ctime" field.
func (_u *NodeUpdateOne) SetCtime(v time.Time) *NodeUpdateOne {
	_u.mutation.SetCtime(v)
	return _u
}

// SetNillableCtime sets the "ctime" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableCtime(v *time.Time) *NodeUpdateOne {
	if v != nil {
		_u.SetCtime(*v)
	}
	return _u
}

// SetCrtime sets the "crtime" field.
func (_u *NodeUpdateOne) SetCrtime(v time.Time) *NodeUpdateOne {
	_u.mutation.SetCrtime(v)
	return _u
}

// SetNillableCrtime sets the "crtime" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableCrtime(v *time.Time) *NodeUpdateOne {
	if v != nil {
		_u.SetCrtime(*v)
	}
	return _u
}

// SetFlags sets the "flags" field.
func (_u *NodeUpdateOne) SetFlags(v uint32) *NodeUpdateOne {
	_u.mutation.ResetFlags()
	_u.mutation.SetFlags(v)
	return _u
}

// SetNillableFlags sets the "flags" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableFlags(v *uint32) *NodeUpdateOne {
	if v != nil {
		_u.SetFlags(*v)
	}
	return _u
}

// AddFlags adds value to the "flags" field.
func (_u *NodeUpdateOne) AddFlags(v int32) *NodeUpdateOne {
	_u.mutation.AddFlags(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *NodeUpdateOne) SetRevision(v string) *NodeUpdateOne {
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableRevision(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdateOne) Mutation() *NodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdateOne) Where(ps ...predicate.Node) *NodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NodeUpdateOne) Select(field string, fields ...string) *NodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Node entity.
func (_u *NodeUpdateOne) Save(ctx context.Context) (*Node, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdateOne) SaveX(ctx context.Context) *Node {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := node.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := node.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Node.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := node.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Node.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := node.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Node.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := node.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "Node.revision": %w`, err)}
		}
	}
	return nil
}

func (_u *NodeUpdateOne) sqlSave(ctx context.Context) (_node *Node, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Node.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, node.FieldID)
		for _, f := range fields {
			if !node.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != node.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(node.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(node.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(node.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(node.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(node.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Nlink(); ok {
		_spec.SetField(node.FieldNlink, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedNlink(); ok {
		_spec.AddField(node.FieldNlink, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(node.FieldContent, field.TypeBytes, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(node.FieldContent, field.TypeBytes)
	}
	if value, ok := _u.mutation.Atime(); ok {
		_spec.SetField(node.FieldAtime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Mtime(); ok {
		_spec.SetField(node.FieldMtime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Ctime(); ok {
		_spec.SetField(node.FieldCtime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Crtime(); ok {
		_spec.SetField(node.FieldCrtime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Flags(); ok {
		_spec.SetField(node.FieldFlags, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedFlags(); ok {
		_spec.AddField(node.FieldFlags, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(node.FieldRevision, field.TypeString, value)
	}
	_node = &Node{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
