// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mandacode-labs/mdrive/ent/node"
	"github.com/mandacode-labs/mdrive/ent/predicate"
	"github.com/mandacode-labs/mdrive/ent/superblock"
)

// SuperblockUpdate is the builder for updating Superblock entities.
type SuperblockUpdate struct {
	config
	hooks    []Hook
	mutation *SuperblockMutation
}

// Where appends a list predicates to the SuperblockUpdate builder.
func (_u *SuperblockUpdate) Where(ps ...predicate.Superblock) *SuperblockUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SuperblockUpdate) SetUpdateTime(v time.Time) *SuperblockUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// AddNodeIDs adds the "nodes" edge to the Node entity by IDs.
func (_u *SuperblockUpdate) AddNodeIDs(ids ...uuid.UUID) *SuperblockUpdate {
	_u.mutation.AddNodeIDs(ids...)
	return _u
}

// AddNodes adds the "nodes" edges to the Node entity.
func (_u *SuperblockUpdate) AddNodes(v ...*Node) *SuperblockUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNodeIDs(ids...)
}

// Mutation returns the SuperblockMutation object of the builder.
func (_u *SuperblockUpdate) Mutation() *SuperblockMutation {
	return _u.mutation
}

// ClearNodes clears all "nodes" edges to the Node entity.
func (_u *SuperblockUpdate) ClearNodes() *SuperblockUpdate {
	_u.mutation.ClearNodes()
	return _u
}

// RemoveNodeIDs removes the "nodes" edge to Node entities by IDs.
func (_u *SuperblockUpdate) RemoveNodeIDs(ids ...uuid.UUID) *SuperblockUpdate {
	_u.mutation.RemoveNodeIDs(ids...)
	return _u
}

// RemoveNodes removes "nodes" edges to Node entities.
func (_u *SuperblockUpdate) RemoveNodes(v ...*Node) *SuperblockUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNodeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SuperblockUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SuperblockUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SuperblockUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SuperblockUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SuperblockUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := superblock.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SuperblockUpdate) check() error {
	if _u.mutation.DriveCleared() && len(_u.mutation.DriveIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Superblock.drive"`)
	}
	return nil
}

func (_u *SuperblockUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(superblock.Table, superblock.Columns, sqlgraph.NewFieldSpec(superblock.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(superblock.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.NodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   superblock.NodesTable,
			Columns: []string{superblock.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNodesIDs(); len(nodes) > 0 && !_u.mutation.NodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   superblock.NodesTable,
			Columns: []string{superblock.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   superblock.NodesTable,
			Columns: []string{superblock.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{superblock.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SuperblockUpdateOne is the builder for updating a single Superblock entity.
type SuperblockUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SuperblockMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *SuperblockUpdateOne) SetUpdateTime(v time.Time) *SuperblockUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// AddNodeIDs adds the "nodes" edge to the Node entity by IDs.
func (_u *SuperblockUpdateOne) AddNodeIDs(ids ...uuid.UUID) *SuperblockUpdateOne {
	_u.mutation.AddNodeIDs(ids...)
	return _u
}

// AddNodes adds the "nodes" edges to the Node entity.
func (_u *SuperblockUpdateOne) AddNodes(v ...*Node) *SuperblockUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNodeIDs(ids...)
}

// Mutation returns the SuperblockMutation object of the builder.
func (_u *SuperblockUpdateOne) Mutation() *SuperblockMutation {
	return _u.mutation
}

// ClearNodes clears all "nodes" edges to the Node entity.
func (_u *SuperblockUpdateOne) ClearNodes() *SuperblockUpdateOne {
	_u.mutation.ClearNodes()
	return _u
}

// RemoveNodeIDs removes the "nodes" edge to Node entities by IDs.
func (_u *SuperblockUpdateOne) RemoveNodeIDs(ids ...uuid.UUID) *SuperblockUpdateOne {
	_u.mutation.RemoveNodeIDs(ids...)
	return _u
}

// RemoveNodes removes "nodes" edges to Node entities.
func (_u *SuperblockUpdateOne) RemoveNodes(v ...*Node) *SuperblockUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNodeIDs(ids...)
}

// Where appends a list predicates to the SuperblockUpdate builder.
func (_u *SuperblockUpdateOne) Where(ps ...predicate.Superblock) *SuperblockUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SuperblockUpdateOne) Select(field string, fields ...string) *SuperblockUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Superblock entity.
func (_u *SuperblockUpdateOne) Save(ctx context.Context) (*Superblock, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SuperblockUpdateOne) SaveX(ctx context.Context) *Superblock {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SuperblockUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SuperblockUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SuperblockUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := superblock.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SuperblockUpdateOne) check() error {
	if _u.mutation.DriveCleared() && len(_u.mutation.DriveIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Superblock.drive"`)
	}
	return nil
}

func (_u *SuperblockUpdateOne) sqlSave(ctx context.Context) (_node *Superblock, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(superblock.Table, superblock.Columns, sqlgraph.NewFieldSpec(superblock.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Superblock.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, superblock.FieldID)
		for _, f := range fields {
			if !superblock.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != superblock.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(superblock.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.NodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   superblock.NodesTable,
			Columns: []string{superblock.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNodesIDs(); len(nodes) > 0 && !_u.mutation.NodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   superblock.NodesTable,
			Columns: []string{superblock.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   superblock.NodesTable,
			Columns: []string{superblock.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Superblock{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{superblock.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
