-- Initial schema: drives, drive_storage, gc_tombstones, nodes, users.

CREATE TABLE "drives" (
    "id" character(32) NOT NULL,
    "create_time" timestamptz NOT NULL,
    "update_time" timestamptz NOT NULL,
    "public_id" character(32) NOT NULL,
    "name" character(64) NOT NULL,
    "description" varchar(255) NULL,
    "provider" character varying NOT NULL DEFAULT 's3',
    "owner_id" character(32) NOT NULL,
    "root_node_id" uuid NULL,
    "deleted_at" timestamptz NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX "drive_public_id" ON "drives" ("public_id");
CREATE INDEX "drive_owner_id" ON "drives" ("owner_id");
CREATE INDEX "drive_deleted_at" ON "drives" ("deleted_at");

CREATE TABLE "drive_storage" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "bucket" character(128) NOT NULL,
    "endpoint" varchar(255) NULL,
    "region" character(32) NOT NULL,
    "access_key" character(255) NOT NULL,
    "secret_key" character(255) NOT NULL,
    "use_path_style" boolean NOT NULL DEFAULT false,
    "drive_id" character(32) NOT NULL,
    "wrapped_dek" varchar(1024) NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "drive_storage_drives_storage" FOREIGN KEY ("drive_id") REFERENCES "drives" ("id") ON DELETE NO ACTION
);

CREATE TABLE "gc_tombstones" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "create_time" timestamptz NOT NULL,
    "update_time" timestamptz NOT NULL,
    "bucket" character(128) NOT NULL,
    "key" varchar(512) NOT NULL,
    "retries" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE "nodes" (
    "id" uuid NOT NULL,
    "create_time" timestamptz NOT NULL,
    "update_time" timestamptz NOT NULL,
    "type" character varying NOT NULL DEFAULT 'file',
    "size" bigint NOT NULL DEFAULT 0,
    "nlink" bigint NOT NULL DEFAULT 0,
    "content" bytea NULL,
    "atime" timestamptz NOT NULL,
    "mtime" timestamptz NOT NULL,
    "ctime" timestamptz NOT NULL,
    "crtime" timestamptz NOT NULL,
    "flags" bigint NOT NULL DEFAULT 0,
    "revision" character(26) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "users" (
    "id" character(32) NOT NULL,
    "create_time" timestamptz NOT NULL,
    "update_time" timestamptz NOT NULL,
    "public_id" character(32) NOT NULL,
    "name" character(255) NOT NULL,
    "email" varchar(255) NULL,
    "provider" character(32) NOT NULL,
    "provider_id" character(255) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "user_provider_provider_id" ON "users" ("provider", "provider_id");

-- Apply CHECK constraint to enforce the node type enum at the DB level.
ALTER TABLE "nodes" ADD CONSTRAINT "nodes_type_check"
    CHECK ("type" IN ('file', 'directory', 'symlink', 'object', 'mount'));
