-- Create "drives" table
CREATE TABLE "drives" (
  "id" character varying NOT NULL,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "public_id" character varying NOT NULL,
  "name" character varying NOT NULL,
  "description" character varying NULL,
  "provider" character varying NOT NULL DEFAULT 's3',
  "owner_id" character varying NOT NULL,
  "root_node_id" uuid NULL,
  PRIMARY KEY ("id")
);
-- Create index "drive_owner_id" to table: "drives"
CREATE INDEX "drive_owner_id" ON "drives" ("owner_id");
-- Create index "drive_public_id" to table: "drives"
CREATE INDEX "drive_public_id" ON "drives" ("public_id");
-- Create index "drives_public_id_key" to table: "drives"
CREATE UNIQUE INDEX "drives_public_id_key" ON "drives" ("public_id");
-- Create "gc_tombstones" table
CREATE TABLE "gc_tombstones" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "bucket" character varying NOT NULL,
  "key" character varying NOT NULL,
  "retries" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);
-- Create "nodes" table
CREATE TABLE "nodes" (
  "id" uuid NOT NULL,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "type" character varying NOT NULL DEFAULT 'file',
  "size" bigint NOT NULL DEFAULT 0,
  "nlink" bigint NOT NULL DEFAULT 1,
  "content" bytea NULL,
  "atime" timestamptz NOT NULL,
  "mtime" timestamptz NOT NULL,
  "ctime" timestamptz NOT NULL,
  "crtime" timestamptz NOT NULL,
  "flags" bigint NOT NULL DEFAULT 0,
  "revision" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "users" table
CREATE TABLE "users" (
  "id" character varying NOT NULL,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "public_id" character varying NOT NULL,
  "name" character varying NOT NULL,
  "email" character varying NULL,
  "provider" character varying NOT NULL,
  "provider_id" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "user_provider_provider_id" to table: "users"
CREATE UNIQUE INDEX "user_provider_provider_id" ON "users" ("provider", "provider_id");
-- Create index "users_public_id_key" to table: "users"
CREATE UNIQUE INDEX "users_public_id_key" ON "users" ("public_id");
-- Create "drive_storage" table
CREATE TABLE "drive_storage" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "bucket" character varying NOT NULL,
  "endpoint" character varying NULL,
  "region" character varying NOT NULL,
  "access_key" character varying NOT NULL,
  "secret_key" character varying NOT NULL,
  "use_path_style" boolean NOT NULL DEFAULT false,
  "drive_id" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "drive_storage_drives_storage" FOREIGN KEY ("drive_id") REFERENCES "drives" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "drive_storage_drive_id_key" to table: "drive_storage"
CREATE UNIQUE INDEX "drive_storage_drive_id_key" ON "drive_storage" ("drive_id");
