// Code generated by ent, DO NOT EDIT.

package superblock

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the superblock type in the database.
	Label = "superblock"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldRootNodeID holds the string denoting the root_node_id field in the database.
	FieldRootNodeID = "root_node_id"
	// EdgeDrive holds the string denoting the drive edge name in mutations.
	EdgeDrive = "drive"
	// Table holds the table name of the superblock in the database.
	Table = "superblocks"
	// DriveTable is the table that holds the drive relation/edge.
	DriveTable = "superblocks"
	// DriveInverseTable is the table name for the Drive entity.
	// It exists in this package in order to avoid circular dependency with the "drive" package.
	DriveInverseTable = "drives"
	// DriveColumn is the table column denoting the drive relation/edge.
	DriveColumn = "drive_superblock"
)

// Columns holds all SQL columns for superblock fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldRootNodeID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "superblocks"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"drive_superblock",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Superblock queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByRootNodeID orders the results by the root_node_id field.
func ByRootNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRootNodeID, opts...).ToFunc()
}

// ByDriveField orders the results by drive field.
func ByDriveField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDriveStep(), sql.OrderByField(field, opts...))
	}
}
func newDriveStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DriveInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, DriveTable, DriveColumn),
	)
}
