// Code generated by ent, DO NOT EDIT.

package superblock

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/mandacode-labs/mdrive/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Superblock {
	return predicate.Superblock(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Superblock {
	return predicate.Superblock(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Superblock {
	return predicate.Superblock(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Superblock {
	return predicate.Superblock(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Superblock {
	return predicate.Superblock(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Superblock {
	return predicate.Superblock(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Superblock {
	return predicate.Superblock(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Superblock {
	return predicate.Superblock(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Superblock {
	return predicate.Superblock(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Superblock {
	return predicate.Superblock(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Superblock {
	return predicate.Superblock(sql.FieldEQ(FieldUpdateTime, v))
}

// RootNodeID applies equality check predicate on the "root_node_id" field. It's identical to RootNodeIDEQ.
func RootNodeID(v uuid.UUID) predicate.Superblock {
	return predicate.Superblock(sql.FieldEQ(FieldRootNodeID, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Superblock {
	return predicate.Superblock(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Superblock {
	return predicate.Superblock(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Superblock {
	return predicate.Superblock(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Superblock {
	return predicate.Superblock(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Superblock {
	return predicate.Superblock(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Superblock {
	return predicate.Superblock(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Superblock {
	return predicate.Superblock(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Superblock {
	return predicate.Superblock(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Superblock {
	return predicate.Superblock(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Superblock {
	return predicate.Superblock(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Superblock {
	return predicate.Superblock(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Superblock {
	return predicate.Superblock(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Superblock {
	return predicate.Superblock(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Superblock {
	return predicate.Superblock(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Superblock {
	return predicate.Superblock(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Superblock {
	return predicate.Superblock(sql.FieldLTE(FieldUpdateTime, v))
}

// RootNodeIDEQ applies the EQ predicate on the "root_node_id" field.
func RootNodeIDEQ(v uuid.UUID) predicate.Superblock {
	return predicate.Superblock(sql.FieldEQ(FieldRootNodeID, v))
}

// RootNodeIDNEQ applies the NEQ predicate on the "root_node_id" field.
func RootNodeIDNEQ(v uuid.UUID) predicate.Superblock {
	return predicate.Superblock(sql.FieldNEQ(FieldRootNodeID, v))
}

// RootNodeIDIn applies the In predicate on the "root_node_id" field.
func RootNodeIDIn(vs ...uuid.UUID) predicate.Superblock {
	return predicate.Superblock(sql.FieldIn(FieldRootNodeID, vs...))
}

// RootNodeIDNotIn applies the NotIn predicate on the "root_node_id" field.
func RootNodeIDNotIn(vs ...uuid.UUID) predicate.Superblock {
	return predicate.Superblock(sql.FieldNotIn(FieldRootNodeID, vs...))
}

// RootNodeIDGT applies the GT predicate on the "root_node_id" field.
func RootNodeIDGT(v uuid.UUID) predicate.Superblock {
	return predicate.Superblock(sql.FieldGT(FieldRootNodeID, v))
}

// RootNodeIDGTE applies the GTE predicate on the "root_node_id" field.
func RootNodeIDGTE(v uuid.UUID) predicate.Superblock {
	return predicate.Superblock(sql.FieldGTE(FieldRootNodeID, v))
}

// RootNodeIDLT applies the LT predicate on the "root_node_id" field.
func RootNodeIDLT(v uuid.UUID) predicate.Superblock {
	return predicate.Superblock(sql.FieldLT(FieldRootNodeID, v))
}

// RootNodeIDLTE applies the LTE predicate on the "root_node_id" field.
func RootNodeIDLTE(v uuid.UUID) predicate.Superblock {
	return predicate.Superblock(sql.FieldLTE(FieldRootNodeID, v))
}

// HasDrive applies the HasEdge predicate on the "drive" edge.
func HasDrive() predicate.Superblock {
	return predicate.Superblock(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, DriveTable, DriveColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDriveWith applies the HasEdge predicate on the "drive" edge with a given conditions (other predicates).
func HasDriveWith(preds ...predicate.Drive) predicate.Superblock {
	return predicate.Superblock(func(s *sql.Selector) {
		step := newDriveStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Superblock) predicate.Superblock {
	return predicate.Superblock(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Superblock) predicate.Superblock {
	return predicate.Superblock(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Superblock) predicate.Superblock {
	return predicate.Superblock(sql.NotPredicates(p))
}
