// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package permissionMocks

import (
	"context"

	"github.com/mandacode-labs/mdrive/internal/permission"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthorizerMock creates a new instance of AuthorizerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizerMock {
	mock := &AuthorizerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthorizerMock is an autogenerated mock type for the Authorizer type
type AuthorizerMock struct {
	mock.Mock
}

type AuthorizerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthorizerMock) EXPECT() *AuthorizerMock_Expecter {
	return &AuthorizerMock_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type AuthorizerMock
func (_mock *AuthorizerMock) Check(ctx context.Context, user string, perm permission.Action, objectType string, objectID string) (bool, error) {
	ret := _mock.Called(ctx, user, perm, objectType, objectID)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, permission.Action, string, string) (bool, error)); ok {
		return returnFunc(ctx, user, perm, objectType, objectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, permission.Action, string, string) bool); ok {
		r0 = returnFunc(ctx, user, perm, objectType, objectID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, permission.Action, string, string) error); ok {
		r1 = returnFunc(ctx, user, perm, objectType, objectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthorizerMock_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type AuthorizerMock_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
//   - user string
//   - perm permission.Action
//   - objectType string
//   - objectID string
func (_e *AuthorizerMock_Expecter) Check(ctx interface{}, user interface{}, perm interface{}, objectType interface{}, objectID interface{}) *AuthorizerMock_Check_Call {
	return &AuthorizerMock_Check_Call{Call: _e.mock.On("Check", ctx, user, perm, objectType, objectID)}
}

func (_c *AuthorizerMock_Check_Call) Run(run func(ctx context.Context, user string, perm permission.Action, objectType string, objectID string)) *AuthorizerMock_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 permission.Action
		if args[2] != nil {
			arg2 = args[2].(permission.Action)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *AuthorizerMock_Check_Call) Return(b bool, err error) *AuthorizerMock_Check_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *AuthorizerMock_Check_Call) RunAndReturn(run func(ctx context.Context, user string, perm permission.Action, objectType string, objectID string) (bool, error)) *AuthorizerMock_Check_Call {
	_c.Call.Return(run)
	return _c
}

// Grant provides a mock function for the type AuthorizerMock
func (_mock *AuthorizerMock) Grant(ctx context.Context, user string, relation string, objectType string, objectID string) error {
	ret := _mock.Called(ctx, user, relation, objectType, objectID)

	if len(ret) == 0 {
		panic("no return value specified for Grant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, user, relation, objectType, objectID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthorizerMock_Grant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Grant'
type AuthorizerMock_Grant_Call struct {
	*mock.Call
}

// Grant is a helper method to define mock.On call
//   - ctx context.Context
//   - user string
//   - relation string
//   - objectType string
//   - objectID string
func (_e *AuthorizerMock_Expecter) Grant(ctx interface{}, user interface{}, relation interface{}, objectType interface{}, objectID interface{}) *AuthorizerMock_Grant_Call {
	return &AuthorizerMock_Grant_Call{Call: _e.mock.On("Grant", ctx, user, relation, objectType, objectID)}
}

func (_c *AuthorizerMock_Grant_Call) Run(run func(ctx context.Context, user string, relation string, objectType string, objectID string)) *AuthorizerMock_Grant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *AuthorizerMock_Grant_Call) Return(err error) *AuthorizerMock_Grant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthorizerMock_Grant_Call) RunAndReturn(run func(ctx context.Context, user string, relation string, objectType string, objectID string) error) *AuthorizerMock_Grant_Call {
	_c.Call.Return(run)
	return _c
}

// ListObjects provides a mock function for the type AuthorizerMock
func (_mock *AuthorizerMock) ListObjects(ctx context.Context, user string, perm permission.Action, objectType string) ([]string, error) {
	ret := _mock.Called(ctx, user, perm, objectType)

	if len(ret) == 0 {
		panic("no return value specified for ListObjects")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, permission.Action, string) ([]string, error)); ok {
		return returnFunc(ctx, user, perm, objectType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, permission.Action, string) []string); ok {
		r0 = returnFunc(ctx, user, perm, objectType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, permission.Action, string) error); ok {
		r1 = returnFunc(ctx, user, perm, objectType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthorizerMock_ListObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObjects'
type AuthorizerMock_ListObjects_Call struct {
	*mock.Call
}

// ListObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - user string
//   - perm permission.Action
//   - objectType string
func (_e *AuthorizerMock_Expecter) ListObjects(ctx interface{}, user interface{}, perm interface{}, objectType interface{}) *AuthorizerMock_ListObjects_Call {
	return &AuthorizerMock_ListObjects_Call{Call: _e.mock.On("ListObjects", ctx, user, perm, objectType)}
}

func (_c *AuthorizerMock_ListObjects_Call) Run(run func(ctx context.Context, user string, perm permission.Action, objectType string)) *AuthorizerMock_ListObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 permission.Action
		if args[2] != nil {
			arg2 = args[2].(permission.Action)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AuthorizerMock_ListObjects_Call) Return(strings []string, err error) *AuthorizerMock_ListObjects_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *AuthorizerMock_ListObjects_Call) RunAndReturn(run func(ctx context.Context, user string, perm permission.Action, objectType string) ([]string, error)) *AuthorizerMock_ListObjects_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type AuthorizerMock
func (_mock *AuthorizerMock) Revoke(ctx context.Context, user string, relation string, objectType string, objectID string) error {
	ret := _mock.Called(ctx, user, relation, objectType, objectID)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, user, relation, objectType, objectID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthorizerMock_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type AuthorizerMock_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - user string
//   - relation string
//   - objectType string
//   - objectID string
func (_e *AuthorizerMock_Expecter) Revoke(ctx interface{}, user interface{}, relation interface{}, objectType interface{}, objectID interface{}) *AuthorizerMock_Revoke_Call {
	return &AuthorizerMock_Revoke_Call{Call: _e.mock.On("Revoke", ctx, user, relation, objectType, objectID)}
}

func (_c *AuthorizerMock_Revoke_Call) Run(run func(ctx context.Context, user string, relation string, objectType string, objectID string)) *AuthorizerMock_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *AuthorizerMock_Revoke_Call) Return(err error) *AuthorizerMock_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthorizerMock_Revoke_Call) RunAndReturn(run func(ctx context.Context, user string, relation string, objectType string, objectID string) error) *AuthorizerMock_Revoke_Call {
	_c.Call.Return(run)
	return _c
}
