{{- if or .Values.secrets.database.password .Values.secrets.valkey.password .Values.secrets.storage.access_key .Values.secrets.storage.secret_key .Values.secrets.crypto.master_key .Values.secrets.auth.encryption_key .Values.secrets.openfga.api_token .Values.secrets.openfga.client_id .Values.secrets.openfga.client_secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mdrive.fullname" . }}
  labels:
    {{- include "mdrive.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.database.password }}
  database-password: {{ .Values.secrets.database.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.valkey.password }}
  valkey-password: {{ .Values.secrets.valkey.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.storage.access_key }}
  storage-access-key: {{ .Values.secrets.storage.access_key | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.storage.secret_key }}
  storage-secret-key: {{ .Values.secrets.storage.secret_key | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.crypto.master_key }}
  crypto-master-key: {{ .Values.secrets.crypto.master_key | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.auth.encryption_key }}
  auth-encryption-key: {{ .Values.secrets.auth.encryption_key | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.openfga.api_token }}
  openfga-api-token: {{ .Values.secrets.openfga.api_token | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.openfga.client_id }}
  openfga-client-id: {{ .Values.secrets.openfga.client_id | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.openfga.client_secret }}
  openfga-client-secret: {{ .Values.secrets.openfga.client_secret | b64enc | quote }}
  {{- end }}
{{- end }}
