// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package userMocks

import (
	"context"

	"github.com/mandacode-labs/mdrive/internal/core/user"
	mock "github.com/stretchr/testify/mock"
)

// NewServiceMock creates a new instance of ServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceMock {
	mock := &ServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceMock is an autogenerated mock type for the Service type
type ServiceMock struct {
	mock.Mock
}

type ServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceMock) EXPECT() *ServiceMock_Expecter {
	return &ServiceMock_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type ServiceMock
func (_mock *ServiceMock) GetByID(ctx context.Context, id string) (*user.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ServiceMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ServiceMock_Expecter) GetByID(ctx interface{}, id interface{}) *ServiceMock_GetByID_Call {
	return &ServiceMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ServiceMock_GetByID_Call) Run(run func(ctx context.Context, id string)) *ServiceMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceMock_GetByID_Call) Return(user1 *user.User, err error) *ServiceMock_GetByID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *ServiceMock_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*user.User, error)) *ServiceMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProviderID provides a mock function for the type ServiceMock
func (_mock *ServiceMock) GetByProviderID(ctx context.Context, provider string, providerID string) (*user.User, error) {
	ret := _mock.Called(ctx, provider, providerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByProviderID")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*user.User, error)); ok {
		return returnFunc(ctx, provider, providerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *user.User); ok {
		r0 = returnFunc(ctx, provider, providerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, provider, providerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_GetByProviderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProviderID'
type ServiceMock_GetByProviderID_Call struct {
	*mock.Call
}

// GetByProviderID is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - providerID string
func (_e *ServiceMock_Expecter) GetByProviderID(ctx interface{}, provider interface{}, providerID interface{}) *ServiceMock_GetByProviderID_Call {
	return &ServiceMock_GetByProviderID_Call{Call: _e.mock.On("GetByProviderID", ctx, provider, providerID)}
}

func (_c *ServiceMock_GetByProviderID_Call) Run(run func(ctx context.Context, provider string, providerID string)) *ServiceMock_GetByProviderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ServiceMock_GetByProviderID_Call) Return(user1 *user.User, err error) *ServiceMock_GetByProviderID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *ServiceMock_GetByProviderID_Call) RunAndReturn(run func(ctx context.Context, provider string, providerID string) (*user.User, error)) *ServiceMock_GetByProviderID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPublicID provides a mock function for the type ServiceMock
func (_mock *ServiceMock) GetByPublicID(ctx context.Context, publicID string) (*user.User, error) {
	ret := _mock.Called(ctx, publicID)

	if len(ret) == 0 {
		panic("no return value specified for GetByPublicID")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, publicID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, publicID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, publicID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_GetByPublicID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPublicID'
type ServiceMock_GetByPublicID_Call struct {
	*mock.Call
}

// GetByPublicID is a helper method to define mock.On call
//   - ctx context.Context
//   - publicID string
func (_e *ServiceMock_Expecter) GetByPublicID(ctx interface{}, publicID interface{}) *ServiceMock_GetByPublicID_Call {
	return &ServiceMock_GetByPublicID_Call{Call: _e.mock.On("GetByPublicID", ctx, publicID)}
}

func (_c *ServiceMock_GetByPublicID_Call) Run(run func(ctx context.Context, publicID string)) *ServiceMock_GetByPublicID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceMock_GetByPublicID_Call) Return(user1 *user.User, err error) *ServiceMock_GetByPublicID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *ServiceMock_GetByPublicID_Call) RunAndReturn(run func(ctx context.Context, publicID string) (*user.User, error)) *ServiceMock_GetByPublicID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ServiceMock
func (_mock *ServiceMock) Update(ctx context.Context, u *user.User) (*user.User, error) {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User) (*user.User, error)); ok {
		return returnFunc(ctx, u)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User) *user.User); ok {
		r0 = returnFunc(ctx, u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *user.User) error); ok {
		r1 = returnFunc(ctx, u)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ServiceMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - u *user.User
func (_e *ServiceMock_Expecter) Update(ctx interface{}, u interface{}) *ServiceMock_Update_Call {
	return &ServiceMock_Update_Call{Call: _e.mock.On("Update", ctx, u)}
}

func (_c *ServiceMock_Update_Call) Run(run func(ctx context.Context, u *user.User)) *ServiceMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.User
		if args[1] != nil {
			arg1 = args[1].(*user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceMock_Update_Call) Return(user1 *user.User, err error) *ServiceMock_Update_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *ServiceMock_Update_Call) RunAndReturn(run func(ctx context.Context, u *user.User) (*user.User, error)) *ServiceMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertFromOIDC provides a mock function for the type ServiceMock
func (_mock *ServiceMock) UpsertFromOIDC(ctx context.Context, cmd *user.CreateCommand) (*user.User, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for UpsertFromOIDC")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.CreateCommand) (*user.User, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.CreateCommand) *user.User); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *user.CreateCommand) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_UpsertFromOIDC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertFromOIDC'
type ServiceMock_UpsertFromOIDC_Call struct {
	*mock.Call
}

// UpsertFromOIDC is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *user.CreateCommand
func (_e *ServiceMock_Expecter) UpsertFromOIDC(ctx interface{}, cmd interface{}) *ServiceMock_UpsertFromOIDC_Call {
	return &ServiceMock_UpsertFromOIDC_Call{Call: _e.mock.On("UpsertFromOIDC", ctx, cmd)}
}

func (_c *ServiceMock_UpsertFromOIDC_Call) Run(run func(ctx context.Context, cmd *user.CreateCommand)) *ServiceMock_UpsertFromOIDC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.CreateCommand
		if args[1] != nil {
			arg1 = args[1].(*user.CreateCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceMock_UpsertFromOIDC_Call) Return(user1 *user.User, err error) *ServiceMock_UpsertFromOIDC_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *ServiceMock_UpsertFromOIDC_Call) RunAndReturn(run func(ctx context.Context, cmd *user.CreateCommand) (*user.User, error)) *ServiceMock_UpsertFromOIDC_Call {
	_c.Call.Return(run)
	return _c
}
